import { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "ko" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  ko: {
    // Navigation
    "nav.mypage": "마이페이지",
    "nav.dashboard": "대시보드",
    "nav.login": "로그인",
    "nav.admin": "관리자 대시보드",
    
    // Auth
    "auth.badge": "스마트한 패션 시작",
    "auth.title": "TruPick 시작하기",
    "auth.subtitle": "Google 계정으로 간편하게 로그인하세요",
    "auth.google": "Google로 계속하기",
    "auth.benefits.title": "로그인하면 이런 혜택이!",
    "auth.benefits.1": "가입 시 무료 피팅 제공",
    "auth.benefits.2": "모든 결과물 저장 및 관리",
    "auth.benefits.3": "맞춤형 스타일 분석 리포트",
    "auth.terms": "로그인 시 이용약관 및 개인정보처리방침에 동의하게 됩니다",
    "auth.agreeToTerms": "이용약관에 동의합니다",
    "auth.termsLink": "이용약관",
    "auth.privacyLink": "개인정보처리방침",
    "auth.agreeRequired": "로그인하려면 이용약관에 동의해주세요",
    "auth.agreeRequiredBoth": "로그인하려면 이용약관과 개인정보처리방침에 모두 동의해주세요",
    "auth.readAndAgree": "확인하기",
    "auth.readCarefully": "아래 내용을 읽고 동의해주세요",
    "auth.agreeAndContinue": "동의합니다",
    "auth.cancel": "취소",
    
    // Dashboard
    "dashboard.welcome": "안녕하세요",
    "dashboard.subtitle": "오늘도 멋진 스타일을 만들어보세요",
    "dashboard.credits": "보유 크레딧",
    "dashboard.buyCredits": "크레딧 충전",
    "dashboard.totalUsage": "총 이용 횟수",
    "dashboard.usageDesc": "지금까지 생성한 피팅 이미지",
    "dashboard.newTryon": "새로운 피팅",
    "dashboard.startNow": "지금 바로 시작하세요",
    "dashboard.createNew": "새로 만들기",
    "dashboard.history": "이용 내역",
    "dashboard.noHistory": "아직 이용 내역이 없습니다",
    "dashboard.createFirst": "첫 피팅 만들기",
    "dashboard.tryonAction": "가상 피팅",
    "dashboard.purchaseAction": "크레딧 구매",
    "dashboard.credit": "크레딧",
    "dashboard.view": "보기",
    "dashboard.hasStyleReport": "스타일 리포트 포함",
    "dashboard.shareStatus": "공유 현황",
    "dashboard.shareProgress": "{n}/{total} 클릭",
    "dashboard.shareRewardEarned": "보상 완료 🎉",
    
    // MyPage
    "mypage.title": "마이페이지",
    "mypage.subtitle": "프로필 관리 및 크레딧 충전",
    "mypage.profile": "내 프로필",
    "mypage.currentCredits": "보유 크레딧",
    "mypage.memberSince": "가입일",
    "mypage.buyCredits": "크레딧 충전",
    "mypage.buyCreditsDesc": "크레딧을 충전하여 더 많은 가상 피팅을 즐겨보세요",
    "mypage.credits": "크레딧",
    "mypage.popular": "인기",
    "mypage.purchase": "구매하기",
    "mypage.paymentNote": "Apple Pay, Cash App Pay 및 모든 주요 카드 결제 가능",
    
    // Promo Codes
    "promo.title": "프로모션 코드",
    "promo.searchPlaceholder": "프로모션 코드 입력",
    "promo.searchLabel": "프로모션 코드 검색",
    "promo.notFound": "유효하지 않은 프로모션 코드입니다",
    "promo.claim": "받기",
    "promo.use": "사용하기",
    "promo.applied": "적용됨",
    "promo.discount": "할인",
    "promo.creditsBonus": "크레딧 추가",
    "promo.myPromoCodes": "보유 프로모션",
    "promo.noPromoCodes": "보유한 프로모션이 없습니다",
    "promo.searchHint": "프로모션 코드를 검색해보세요",
    "promo.selectDiscount": "할인 쿠폰 선택",
    
    // Purchase Flow
    "purchase.promoStep": "프로모션 선택",
    "purchase.packageStep": "크레딧 선택",
    "purchase.paymentStep": "결제",
    "purchase.skip": "다음",
    "purchase.next": "다음",
    "purchase.back": "이전",
    "purchase.summary": "주문 내역",
    "purchase.total": "결제 금액",
    "purchase.pay": "결제하기",
    "purchase.lemonSqueezyNote": "할인 코드는 결제창에 최종 입력해야 적용됩니다.",
    "purchase.redirecting": "결제 페이지로 이동합니다...",
    "purchase.processing": "결제 처리 중",
    "purchase.success": "결제가 완료되었습니다!",
    "purchase.error": "결제 처리에 실패했습니다",
    
    // Upload - No Credits
    "upload.noCredits.title": "크레딧이 없습니다",
    "upload.noCredits.description": "피팅 분석을 시작하려면 크레딧이 필요합니다. 크레딧을 구매해주세요.",
    "upload.noCredits.cancel": "취소",
    "upload.noCredits.purchase": "크레딧 구매하기",
    
    // Landing
    "hero.badge": "AI 가상 피팅 + 스타일 분석",
    "hero.title1": "옷을 입어보지 않아도",
    "hero.title2": "내 모습을 확인하세요",
    "hero.subtitle": "미리 입어보고, 실패 없이 구매하세요.",
    "hero.cta": "시작하기",
    "feature.speed": "30초 만에 완성",
    "feature.face": "얼굴 그대로 유지",
    "feature.report": "스타일 분석 리포트",
    "benefits.title": "이런 분들을 위해 만들었어요",
    "benefits.subtitle": "가상 피팅 + 맞춤 스타일 솔루션으로 더 스마트한 패션 라이프",
    "benefits.1": "온라인 쇼핑 전 가상 피팅",
    "benefits.2": "내 체형에 맞는 옷인지 확인",
    "benefits.3": "나와 비슷한 체형의 셀럽 스타일 참고",
    "benefits.4": "개인 맞춤 브랜드 추천",
    "howto.title": "어떻게 사용하나요?",
    "howto.subtitle": "4단계로 가상 피팅 + 스타일 분석 완성",
    "howto.step1.title": "전신 사진 업로드",
    "howto.step1.desc": "정면을 바라보는 전신 사진을 올려주세요",
    "howto.step2.title": "옷 사진 선택",
    "howto.step2.desc": "입어보고 싶은 상의, 하의 이미지를 추가하세요",
    "howto.step3.title": "스타일 정보 입력",
    "howto.step3.desc": "체형, TPO, 선호 스타일, 패션 고민을 입력하세요",
    "howto.step4.title": "결과 확인",
    "howto.step4.desc": "가상 피팅 이미지 + 스타일 분석 리포트를 받아보세요",
    "cta.title": "지금 바로 체험해보세요",
    "cta.subtitle": "회원가입 없이 바로 시작",
    "cta.button": "무료로 시작하기",
    "footer.copyright": "© 2025 Trukin. All rights reserved.",
    "footer.privacy": "개인정보처리방침",
    "footer.terms": "이용약관",
    "footer.refund": "환불정책",
    "footer.feedback": "문의하기",
    "footer.companyInfo": "Trukin | 대표자: 정예준 (Yejoon Jeong) | 이메일: admin@trukin.app",
    
    // Navigation extras
    "nav.feedback": "문의하기",
    "nav.loggedIn": "로그인됨",
    "nav.logout": "로그아웃",
    
    // Feedback
    "feedback.title": "문의하기",
    "feedback.subtitle": "버그 신고, 기능 요청, 문의사항을 남겨주세요",
    "feedback.button": "문의하기",
    "feedback.newTicket": "새 문의 작성",
    "feedback.myTickets": "내 문의 내역",
    "feedback.categoryLabel": "문의 유형",
    "feedback.selectCategory": "유형을 선택하세요",
    "feedback.category.bug": "버그 신고",
    "feedback.category.feature": "기능 요청",
    "feedback.category.inquiry": "일반 문의",
    "feedback.category.other": "기타",
    "feedback.titleLabel": "제목",
    "feedback.titlePlaceholder": "문의 제목을 입력하세요",
    "feedback.contentLabel": "내용",
    "feedback.contentPlaceholder": "문의 내용을 자세히 적어주세요",
    "feedback.attachments": "첨부 이미지",
    "feedback.addImage": "추가",
    "feedback.attachmentHint": "최대 3장, 5MB 이하 이미지",
    "feedback.maxAttachments": "최대 3장까지 첨부할 수 있습니다",
    "feedback.imageOnly": "이미지 파일만 첨부할 수 있습니다",
    "feedback.fileTooLarge": "파일 크기는 5MB 이하여야 합니다",
    "feedback.loginRequired": "로그인이 필요합니다",
    "feedback.fillRequired": "모든 필수 항목을 입력해주세요",
    "feedback.submit": "제출하기",
    "feedback.submitting": "제출 중...",
    "feedback.submitSuccess": "문의가 접수되었습니다",
    "feedback.submitError": "문의 접수에 실패했습니다",
    "feedback.noTickets": "문의 내역이 없습니다",
    "feedback.status.pending": "대기중",
    "feedback.status.inProgress": "처리중",
    "feedback.status.resolved": "완료",
    "feedback.status.closed": "종료",
    "feedback.backToList": "목록으로",
    "feedback.notFound": "문의를 찾을 수 없습니다",
    "feedback.loadError": "문의를 불러오는데 실패했습니다",
    "feedback.conversation": "대화 내역",
    "feedback.noReplies": "아직 답변이 없습니다",
    "feedback.admin": "관리자",
    "feedback.you": "나",
    "feedback.replyPlaceholder": "추가 내용을 입력하세요...",
    "feedback.sendReply": "보내기",
    "feedback.replySuccess": "답변이 전송되었습니다",
    "feedback.replyError": "답변 전송에 실패했습니다",
    "feedback.ticketClosed": "종료된 문의입니다",
    
    // Upload
    "upload.back": "돌아가기",
    "upload.title": "이미지 업로드",
    "upload.subtitle": "전신 사진과 입어보고 싶은 옷을 업로드하세요",
    "upload.person.label": "내 사진",
    "upload.person.desc": "정면을 바라보는 사진",
    "upload.person.req1": "",
    "upload.person.req2": "",
    "upload.person.req3": "",
    "upload.person.req4": "",
    "upload.person.req5": "",
    
    // Unified Photo Guide (collapsible)
    "upload.guide.title": "📸 촬영 가이드 보기",
    "upload.guide.personSection": "내 사진 촬영 팁",
    "upload.guide.person.pose": "팔을 몸에 붙이지 말고 옆으로 살짝 벌려주세요 (A-Pose)",
    "upload.guide.person.attire": "헐렁하거나 두꺼운 옷(패딩 등)을 입으면 체형 인식이 어려워요",
    "upload.guide.person.background": "복잡한 배경은 피해주세요",
    "upload.guide.person.size": "내 모습이 선명하게 나와야 해요 (너무 멀리서 찍어 내 몸이 작게 나오는 사진은 피해주세요)",
    "upload.guide.person.noGroup": "단체 사진은 사용할 수 없어요",
    "upload.guide.person.noHolding": "물건을 들고 있으면 퀄리티가 떨어질 수 있어요",
    "upload.guide.garmentSection": "옷 사진 촬영 팁",
    "upload.guide.garment.flatLay": "옷만 단독으로 나온 깨끗한 사진이 가장 좋아요",
    "upload.guide.garment.noOverlap": "여러 벌 겹쳐진 사진은 피해주세요",
    "upload.guide.garment.frontView": "정면 촬영 권장 (뒷면 불가)",
    "upload.guide.garment.wrinkle": "접히거나 구겨진 옷은 피해주세요",
    "upload.guide.lengthMatch.title": "⚠️ 소매/바지 길이를 맞춰주세요",
    "upload.guide.lengthMatch.top.desc": "내 사진이 긴팔이면 → 긴팔 옷 업로드\n내 사진이 반팔이면 → 반팔 옷 업로드",
    "upload.guide.lengthMatch.bottom.desc": "내 사진이 긴바지면 → 긴바지 업로드\n내 사진이 반바지면 → 반바지 업로드",
    "upload.guide.lengthMatch.full.desc": "상의와 하의 모두 길이가 비슷해야 자연스러워요",
    "upload.guide.lengthMatch.reason": "길이가 다르면 원래 옷 일부가 보일 수 있어요",
    "upload.top.label": "상의",
    "upload.top.desc": "입어보고 싶은 상의 이미지",
    "upload.top.req1": "어떤 배경이든 OK! 편집 없이 바로 업로드",
    "upload.top.req2": "정면 촬영 권장 (뒷면 불가)",
    "upload.top.req3": "접히거나 구겨진 옷은 피해주세요",
    "upload.top.req4": "여러 벌 겹쳐진 사진 불가",
    "upload.top.req5": "",
    "upload.bottom.label": "하의",
    "upload.bottom.desc": "하의 없으면 AI가 자동 생성",
    "upload.bottom.descFull": "입어보고 싶은 하의 이미지",
    "upload.bottom.req1": "상의가 보이지 않는 하의만 담긴 사진이 가장 정확해요",
    "upload.bottom.req2": "정면 촬영 권장",
    "upload.optional": "선택",
    "upload.dropzone": "클릭하거나 드래그",
    "upload.format": "JPG, PNG, BMP (최대 5MB)",
    "upload.requirements": "이미지 요구사항",
    "upload.submit": "피팅 + 분석 시작하기",
    "upload.submitting": "처리 중...",
    "upload.required": "전신 사진과 상의는 필수입니다",
    "upload.required.label": "필수",
    "upload.fullModeRequired": "전신 모드에서는 상의와 하의 모두 필수입니다",
    "upload.confirm.title": "업로드 현황 확인",
    "upload.confirm.description": "업로드 항목을 확인하세요.",
    "upload.confirm.person": "전신 사진",
    "upload.confirm.top": "상의",
    "upload.confirm.bottom": "하의",
    "upload.confirm.outfit": "전체 코디 사진",
    "upload.confirm.profile": "스타일 프로필",
    "upload.confirm.ready": "준비 완료",
    "upload.confirm.notReady": "미입력",
    "upload.confirm.optional": "선택사항",
    "upload.confirm.start": "최종 시작하기",
    "upload.confirm.cancel": "취소",
    "upload.confirm.bottomNotice": "하의 미입력 시 AI가 자동으로 생성합니다",
    "upload.confirm.qualityNotice": "결과물은 업로드된 사진의 화질과 조건에 따라 달라질 수 있습니다",
    "upload.confirm.dashboardNotice": "분석 완료 후 대시보드에서 결과를 다시 확인할 수 있어요",
    "upload.confirm.accuracyTitle": "정확도 높이는 팁",
    "upload.confirm.topAccuracyTip": "하의가 보이지 않는 상의만 담긴 사진이 가장 정확해요",
    "upload.confirm.bottomAccuracyTip": "상의가 보이지 않는 하의만 담긴 사진이 가장 정확해요",
    "upload.example": "예시",
    
    // Upload Validation
    "upload.validation.garmentPhotoType": "옷 사진 타입을 선택해주세요",
    "upload.validation.runMode": "피팅 모드를 선택해주세요",
    
    // Upload Mode Selection
    "upload.mode.title": "피팅 모드 선택",
    "upload.mode.top": "상의 피팅",
    "upload.mode.topDesc": "하의는 그대로 유지",
    "upload.mode.bottom": "하의 피팅",
    "upload.mode.bottomDesc": "상의는 그대로 유지",
    "upload.mode.full": "전체 코디",
    "upload.mode.fullDesc": "상의 + 하의 모두 교체",
    "upload.mode.fullDescSingle": "한 장의 코디 사진으로 피팅",
    "upload.mode.dressNotice": "원피스/드레스는 '전체 코디' 모드를 이용해주세요.",
    "upload.mode.fullWarning": "⚠️ 전체 코디 모드는 옷 사진의 상의+하의 전체를 복사합니다. 예: 반팔 티+반바지 사진 → 결과도 반팔+반바지. 상의만 바꾸려면 '상의 피팅'을 선택하세요.",
    "upload.mode.credit": "크레딧",
    
    // Full Mode Sub-selection
    "upload.fullMode.typeTitle": "옷 사진 업로드 방식",
    "upload.fullMode.separate": "상의 / 하의 따로",
    "upload.fullMode.separateDesc": "서로 다른 상의, 하의 2장",
    "upload.fullMode.single": "한 장에 전체 코디",
    "upload.fullMode.singleDesc": "상하의가 함께 있는 1장",
    
    // Outfit upload
    "upload.outfit.label": "전체 코디 사진",
    "upload.outfit.desc": "상의와 하의가 함께 보이는 옷 사진",
    "upload.outfit.req1": "상의와 하의가 모두 보여야 해요",
    "upload.outfit.req2": "정면 촬영 권장",
    "upload.outfitRequired": "전체 코디 사진이 필요합니다",
    
    // Mode-specific Person Photo Guidelines
    "upload.person.guide.top": "상반신 사진만으로도 충분해요! 허리 라인까지만 명확하게 보이면 자연스럽게 입혀집니다. (물론 전신 사진도 가능합니다.)",
    "upload.person.guide.bottom": "반드시 골반부터 발끝(신발)까지 다 나온 사진을 사용해 주세요. 얼굴은 나오지 않아도 괜찮지만, 하체 라인이 잘리면 바지 핏이 어색해질 수 있습니다.",
    "upload.person.guide.full": "머리부터 발끝까지 모두 포함된 전신 사진이 필수입니다. 상·하의의 조화로운 실루엣을 위해 전신 구도가 가장 정확합니다.",
    
    // Common Person Photo Guidelines
    "upload.person.commonGuide.title": "공통 촬영 팁",
    "upload.person.commonGuide.pose": "포즈: 팔을 몸에 붙이지 말고 옆으로 살짝 벌려주세요 (A-Pose)",
    "upload.person.commonGuide.attire": "복장: 헐렁하거나 두꺼운 옷(패딩 등)을 입으면 체형 인식이 어려워 피팅 결과가 부정확해질 수 있어요",
    "upload.person.commonGuide.angle": "구도: 카메라를 정면으로 응시하고, 수평으로 촬영",
    
    // Garment Photo Guidelines based on type
    "upload.garment.flatLay.main": "옷만 단독으로 나온 깨끗한 사진이 가장 좋아요.",
    "upload.garment.flatLay.tip1": "바닥에 평평하게 펴서 찍은 사진",
    "upload.garment.flatLay.tip2": "배경에 다른 물건이나 손가락이 나오지 않아야 함",
    "upload.garment.flatLay.tip3": "옷의 주름을 최대한 펴서 촬영",
    "upload.garment.model.main": "다른 모델이 입고 있는 화보 사진도 괜찮아요!",
    "upload.garment.model.tip1": "옷의 형태가 명확히 보이는 사진 (가방/손/머리카락이 옷을 가리지 않는 사진)",
    "upload.garment.model.tip2": "단순한 포즈 (너무 꼬인 포즈는 결과가 깨질 수 있음)",
    
    // Style Profile
    "profile.title": "스타일 프로필",
    "profile.subtitle": "더 정확한 스타일 분석을 위해 정보를 입력해주세요",
    "profile.gender.label": "성별",
    "profile.gender.male": "남성",
    "profile.gender.female": "여성",
    "profile.gender.other": "기타",
    "profile.height": "키",
    "profile.heightPlaceholder": "예: 170cm",
    "profile.multiSelect": "복수 선택 가능",
    "profile.other": "기타",
    "profile.otherPlaceholder": "직접 입력해주세요...",
    "profile.bodyType.label": "체형",
    "profile.bodyType.upperHeavy": "상체 통통",
    "profile.bodyType.lowerHeavy": "하체 통통",
    "profile.bodyType.wideShoulders": "어깨 넓음",
    "profile.bodyType.narrowShoulders": "어깨 좁음",
    "profile.bodyType.straight": "일자형",
    "profile.bodyType.slim": "마른 체형",
    "profile.occasion.label": "착용 목적 (TPO)",
    "profile.occasion.daily": "데일리",
    "profile.occasion.date": "데이트",
    "profile.occasion.work": "출근",
    "profile.occasion.interview": "면접",
    "profile.occasion.event": "행사",
    "profile.occasion.travel": "여행",
    "profile.style.label": "선호 스타일",
    "profile.style.minimal": "미니멀",
    "profile.style.casual": "캐주얼",
    "profile.style.street": "스트릿",
    "profile.style.formal": "포멀",
    "profile.style.romantic": "로맨틱",
    "profile.style.vintage": "빈티지",
    "profile.concerns.label": "패션 고민 / 목표",
    "profile.concerns.placeholder": "예: 다리가 길어 보이면 좋겠어요, 어깨가 좁아 보이게 하고 싶어요...",
    "profile.reportNotice": "스타일 리포트는 이 결과 화면에서만 확인 가능하며, 대시보드에서는 다시 볼 수 없습니다.",
    
    // Country Selection
    "profile.country.label": "선호 국가/지역",
    "profile.country.hint": "해당 국가에서 유행하는 스타일, 연예인, 브랜드를 기반으로 분석해드려요",
    "profile.country.placeholder": "예: 미국, 한국, 일본...",
    
    // Fitting Options
    "profile.fittingOptions.title": "피팅 옵션",
    "profile.fittingOptions.subtitle": "피팅 품질과 옷 사진 타입을 선택하세요",
    "profile.runMode.label": "피팅 모드",
    "profile.runMode.performance": "빠른 피팅",
    "profile.runMode.performanceDesc": "가벼운 티셔츠나 심플한 디자인에 추천해요",
    "profile.runMode.quality": "정밀 피팅",
    "profile.runMode.qualityDesc": "복잡한 패턴이나 고화질 결과물을 원할 때 추천해요",
    "profile.garmentType.label": "옷 사진 타입",
    "profile.garmentType.flatLay": "옷만 있는 사진",
    "profile.garmentType.flatLayDesc": "옷걸이 사진 또는 배경을 지운 사진",
    "profile.garmentType.model": "모델 착용 사진",
    "profile.garmentType.modelDesc": "쇼핑몰 모델이나 화보 사진에서 옷을 가져오고 싶을 때",
    
    // Result
    "result.title": "가상 피팅 결과",
    "result.processing": "AI가 열심히 작업 중이에요",
    "result.wait": "약 30초 정도 소요됩니다",
    "result.waitFull": "전체 코디 모드는 약 1분 정도 소요됩니다",
    "result.progress.top": "상의를 입어보는 중...",
    "result.progress.bottom": "하의를 매칭하는 중...",
    "result.complete": "피팅 완료!",
    "result.download": "다운로드",
    "result.share": "공유하기",
    "result.retry": "다시 시도",
    "result.new": "새로 만들기",
    "result.error": "오류가 발생했습니다",
    "result.errorGuide": "에러 화면을 캡쳐하여 문의하시면 크레딧 보상 또는 환불을 도와드립니다.",
    "result.contactUs": "문의하기",
    "result.imageTab": "피팅 이미지",
    "result.reportTab": "스타일 리포트",
    "result.estimatedTime": "예상 소요: 10~20초",
    "result.estimatedTimeFull": "예상 소요: 25~35초",
    "result.stepLabel": "단계",
    "result.leaveWarningNotice": "페이지를 떠나면 결과를 받지 못할 수 있습니다.",
    "result.reportDashboardNotice": "스타일 리포트는 이 화면에서만 확인 가능합니다. 대시보드에서는 다시 볼 수 없으니 캡쳐해두세요!",
    
    // Style Report
    "report.title": "스타일 분석 리포트",
    "report.subtitle": "AI가 분석한 당신의 코디",
    "report.celebrityMatch": "연예인 스타일 매칭",
    "report.brandCuration": "추천 브랜드",
    "report.actionPlan": "스타일 액션 플랜",
    "report.fittingGuide": "피팅 가이드",
    "report.styleTags": "스타일 태그",
    "report.analyzing": "AI가 스타일을 분석하고 있어요...",
    "report.noData": "분석 결과를 불러올 수 없습니다",
    
    // Share Reward
    "share.earnCredits": "공유하고 크레딧 받기!",
    "share.earnCreditsDesc": "친구들에게 공유하면 무료 크레딧 1개를 드려요",
    "share.rewardComplete": "보상 지급 완료!",
    "share.rewardCompleteDesc": "크레딧 1개가 지급되었어요",
    "share.clicks": "클릭 수",
    "share.clicksRemaining": "{n}번 더 클릭되면 보상 지급!",
    "share.creditEarned": "+1 크레딧 획득!",
    "share.creating": "링크 생성 중...",
    "share.createLink": "공유 링크 만들기",
    "share.linkCopied": "링크가 복사되었어요",
    "share.textCopied": "공유 텍스트가 복사되었어요",
    "share.refreshed": "상태가 업데이트되었어요",
    "share.copyText": "텍스트 복사",
    "share.checkStatus": "상태 확인",
    "share.instruction1": "인스타그램 스토리에 이미지와 함께 공유하세요",
    "share.instruction2": "링크를 꼭 포함해주세요",
    "share.instruction3": "3명이 클릭하면 크레딧 1개 자동 지급!",
    "share.shareTemplate": "TruPick으로 가상 피팅해봤어요! 내 모습이 어때 보여?\n\n지금 바로 체험하기\n{url}",
    
    // Share Page
    "share.loading": "로딩 중...",
    "share.title": "TruPick에 오신 것을 환영해요!",
    "share.subtitle": "AI 가상 피팅으로 온라인 쇼핑 전 미리 입어보세요",
    "share.alreadyVisited": "이미 방문하셨네요!",
    "share.tryNow": "지금 바로 체험하기",
    "share.freeCredits": "가입 시 무료 피팅 제공",
    "share.errorTitle": "링크를 찾을 수 없어요",
    "share.errorSubtitle": "유효하지 않거나 만료된 링크예요",
    "share.goHome": "홈으로 가기",
  },
  en: {
    // Navigation
    "nav.mypage": "My Page",
    "nav.dashboard": "Dashboard",
    "nav.login": "Login",
    "nav.admin": "Admin Dashboard",
    
    // Auth
    "auth.badge": "Smart Fashion Starts Here",
    "auth.title": "Get Started with TruPick",
    "auth.subtitle": "Sign in easily with your Google account",
    "auth.google": "Continue with Google",
    "auth.benefits.title": "Benefits of signing in",
    "auth.benefits.1": "Free try-on credits on signup",
    "auth.benefits.2": "Save and manage all results",
    "auth.benefits.3": "Personalized style analysis reports",
    "auth.terms": "By signing in, you agree to our Terms of Service and Privacy Policy",
    "auth.agreeToTerms": "I agree to the Terms of Service",
    "auth.termsLink": "Terms of Service",
    "auth.privacyLink": "Privacy Policy",
    "auth.agreeRequired": "Please agree to the Terms of Service to continue",
    "auth.agreeRequiredBoth": "Please agree to both Terms of Service and Privacy Policy to continue",
    "auth.readAndAgree": "View",
    "auth.readCarefully": "Please read and agree to the following",
    "auth.agreeAndContinue": "I Agree",
    "auth.cancel": "Cancel",
    
    // Dashboard
    "dashboard.welcome": "Hello",
    "dashboard.subtitle": "Create amazing styles today",
    "dashboard.credits": "Credits",
    "dashboard.buyCredits": "Buy Credits",
    "dashboard.totalUsage": "Total Usage",
    "dashboard.usageDesc": "Try-on images created so far",
    "dashboard.newTryon": "New Try-On",
    "dashboard.startNow": "Start right now",
    "dashboard.createNew": "Create New",
    "dashboard.history": "Usage History",
    "dashboard.noHistory": "No usage history yet",
    "dashboard.createFirst": "Create your first try-on",
    "dashboard.tryonAction": "Virtual Try-On",
    "dashboard.purchaseAction": "Credit Purchase",
    "dashboard.credit": "credit",
    "dashboard.view": "View",
    "dashboard.hasStyleReport": "Style Report Included",
    "dashboard.shareStatus": "Share Status",
    "dashboard.shareProgress": "{n}/{total} clicks",
    "dashboard.shareRewardEarned": "Reward Earned 🎉",
    
    // MyPage
    "mypage.title": "My Page",
    "mypage.subtitle": "Manage profile and buy credits",
    "mypage.profile": "My Profile",
    "mypage.currentCredits": "Current Credits",
    "mypage.memberSince": "Member Since",
    "mypage.buyCredits": "Buy Credits",
    "mypage.buyCreditsDesc": "Purchase credits to enjoy more virtual try-ons",
    "mypage.credits": "credits",
    "mypage.popular": "Popular",
    "mypage.purchase": "Purchase",
    "mypage.paymentNote": "Apple Pay, Cash App Pay, and all major cards accepted",
    
    // Promo Codes
    "promo.title": "Promo Codes",
    "promo.searchPlaceholder": "Enter promo code",
    "promo.searchLabel": "Search promo code",
    "promo.notFound": "Invalid promo code",
    "promo.claim": "Claim",
    "promo.use": "Use",
    "promo.applied": "applied",
    "promo.discount": "off",
    "promo.creditsBonus": "credits bonus",
    "promo.myPromoCodes": "My Promo Codes",
    "promo.noPromoCodes": "No promo codes yet",
    "promo.searchHint": "Search for promo codes",
    "promo.selectDiscount": "Select discount coupon",
    
    // Purchase Flow
    "purchase.promoStep": "Select Promo",
    "purchase.packageStep": "Select Package",
    "purchase.paymentStep": "Payment",
    "purchase.skip": "Skip",
    "purchase.next": "Next",
    "purchase.back": "Back",
    "purchase.summary": "Order Summary",
    "purchase.total": "Total",
    "purchase.pay": "Pay Now",
    "purchase.lemonSqueezyNote": "Discount codes must be entered in the checkout page to apply.",
    "purchase.redirecting": "Redirecting to payment page...",
    "purchase.processing": "Processing payment",
    "purchase.success": "Payment completed!",
    "purchase.error": "Payment failed",
    
    // Upload - No Credits
    "upload.noCredits.title": "No Credits Available",
    "upload.noCredits.description": "You need credits to start a try-on analysis. Please purchase credits.",
    "upload.noCredits.cancel": "Cancel",
    "upload.noCredits.purchase": "Buy Credits",
    
    // Landing
    "hero.badge": "AI Virtual Try-On + Style Analysis",
    "hero.title1": "See yourself in any outfit",
    "hero.title2": "without trying it on",
    "hero.subtitle": "Try First, Buy Better.",
    "hero.cta": "Get Started",
    "feature.speed": "Done in 30 seconds",
    "feature.face": "Keep your real face",
    "feature.report": "Style Analysis Report",
    "benefits.title": "Perfect for you",
    "benefits.subtitle": "Virtual fitting + personalized style solutions for smarter fashion",
    "benefits.1": "Try before you buy online",
    "benefits.2": "Check if clothes fit your body type",
    "benefits.3": "Get celebrity style inspiration for your body",
    "benefits.4": "Personalized brand recommendations",
    "howto.title": "How does it work?",
    "howto.subtitle": "Virtual fitting + style analysis in 4 steps",
    "howto.step1.title": "Upload your photo",
    "howto.step1.desc": "A front-facing full-body photo works best",
    "howto.step2.title": "Choose your outfit",
    "howto.step2.desc": "Add the top and bottom images you want to try",
    "howto.step3.title": "Enter style info",
    "howto.step3.desc": "Body type, occasion, preferred style, fashion goals",
    "howto.step4.title": "Get your result",
    "howto.step4.desc": "Receive try-on image + style analysis report",
    "cta.title": "Try it now",
    "cta.subtitle": "No sign up required",
    "cta.button": "Start Free",
    "footer.copyright": "© 2025 Trukin. All rights reserved.",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",
    "footer.refund": "Refund Policy",
    "footer.feedback": "Contact Us",
    "footer.companyInfo": "Trukin | Owner: Yejoon Jeong | Email: admin@trukin.app",
    
    // Navigation extras
    "nav.feedback": "Contact",
    "nav.loggedIn": "Logged in",
    "nav.logout": "Log out",
    
    // Feedback
    "feedback.title": "Contact Us",
    "feedback.subtitle": "Report bugs, request features, or ask questions",
    "feedback.button": "Contact",
    "feedback.newTicket": "New Inquiry",
    "feedback.myTickets": "My Inquiries",
    "feedback.categoryLabel": "Category",
    "feedback.selectCategory": "Select a category",
    "feedback.category.bug": "Bug Report",
    "feedback.category.feature": "Feature Request",
    "feedback.category.inquiry": "General Inquiry",
    "feedback.category.other": "Other",
    "feedback.titleLabel": "Title",
    "feedback.titlePlaceholder": "Enter a title",
    "feedback.contentLabel": "Content",
    "feedback.contentPlaceholder": "Describe your inquiry in detail",
    "feedback.attachments": "Attachments",
    "feedback.addImage": "Add",
    "feedback.attachmentHint": "Max 3 images, up to 5MB each",
    "feedback.maxAttachments": "Maximum 3 images allowed",
    "feedback.imageOnly": "Only image files are allowed",
    "feedback.fileTooLarge": "File size must be under 5MB",
    "feedback.loginRequired": "Please log in first",
    "feedback.fillRequired": "Please fill in all required fields",
    "feedback.submit": "Submit",
    "feedback.submitting": "Submitting...",
    "feedback.submitSuccess": "Inquiry submitted successfully",
    "feedback.submitError": "Failed to submit inquiry",
    "feedback.noTickets": "No inquiries yet",
    "feedback.status.pending": "Pending",
    "feedback.status.inProgress": "In Progress",
    "feedback.status.resolved": "Resolved",
    "feedback.status.closed": "Closed",
    "feedback.backToList": "Back to list",
    "feedback.notFound": "Inquiry not found",
    "feedback.loadError": "Failed to load inquiry",
    "feedback.conversation": "Conversation",
    "feedback.noReplies": "No replies yet",
    "feedback.admin": "Admin",
    "feedback.you": "You",
    "feedback.replyPlaceholder": "Add more information...",
    "feedback.sendReply": "Send",
    "feedback.replySuccess": "Reply sent",
    "feedback.replyError": "Failed to send reply",
    "feedback.ticketClosed": "This inquiry is closed",
    
    // Upload
    "upload.back": "Back",
    "upload.title": "Upload Images",
    "upload.subtitle": "Upload your photo and the clothes you want to try",
    "upload.person.label": "My Photo",
    "upload.person.desc": "Front-facing photo",
    "upload.person.req1": "",
    "upload.person.req2": "",
    "upload.person.req3": "",
    "upload.person.req4": "",
    "upload.person.req5": "",
    
    // Unified Photo Guide (collapsible)
    "upload.guide.title": "📸 View Photo Guide",
    "upload.guide.personSection": "My Photo Tips",
    "upload.guide.person.pose": "Spread arms slightly to the side, not against your body (A-Pose)",
    "upload.guide.person.attire": "Loose or thick clothing (like puffer jackets) may affect body detection",
    "upload.guide.person.background": "Avoid busy backgrounds",
    "upload.guide.person.size": "Your figure should be clearly visible (avoid photos taken from far away where your body appears small)",
    "upload.guide.person.noGroup": "Group photos cannot be used",
    "upload.guide.person.noHolding": "Holding objects may reduce quality",
    "upload.guide.garmentSection": "Garment Photo Tips",
    "upload.guide.garment.flatLay": "Clean photos showing only the garment work best",
    "upload.guide.garment.noOverlap": "Avoid photos with multiple layered items",
    "upload.guide.garment.frontView": "Front view recommended (no back view)",
    "upload.guide.garment.wrinkle": "Avoid folded or wrinkled clothes",
    "upload.guide.lengthMatch.title": "⚠️ Match sleeve/pants length",
    "upload.guide.lengthMatch.top.desc": "If your photo has long sleeves → upload long sleeve\nIf your photo has short sleeves → upload short sleeve",
    "upload.guide.lengthMatch.bottom.desc": "If your photo has long pants → upload long pants\nIf your photo has shorts → upload shorts",
    "upload.guide.lengthMatch.full.desc": "Both top and bottom lengths should match for natural results",
    "upload.guide.lengthMatch.reason": "Mismatched lengths may cause original clothing to show through",
    "upload.top.label": "Top",
    "upload.top.desc": "The top you want to try on",
    "upload.top.req1": "Any background OK! Upload directly without editing",
    "upload.top.req2": "Front view recommended (no back)",
    "upload.top.req3": "Avoid folded or wrinkled clothes",
    "upload.top.req4": "No multiple layered items",
    "upload.top.req5": "",
    "upload.bottom.label": "Bottom",
    "upload.bottom.desc": "AI will generate if not provided",
    "upload.bottom.descFull": "The bottom you want to try on",
    "upload.bottom.req1": "Photos with only bottoms (no top visible) give the best accuracy",
    "upload.bottom.req2": "Front view recommended",
    "upload.optional": "Optional",
    "upload.dropzone": "Click or drag to upload",
    "upload.format": "JPG, PNG, BMP (max 5MB)",
    "upload.requirements": "Image Requirements",
    "upload.submit": "Generate Try-On + Analysis",
    "upload.submitting": "Processing...",
    "upload.required": "Photo and top are required",
    "upload.required.label": "Required",
    "upload.fullModeRequired": "Both top and bottom are required for full outfit mode",
    "upload.confirm.title": "Upload Summary",
    "upload.confirm.description": "Please review your uploads.",
    "upload.confirm.person": "Full Body Photo",
    "upload.confirm.top": "Top",
    "upload.confirm.bottom": "Bottom",
    "upload.confirm.outfit": "Full Outfit Photo",
    "upload.confirm.profile": "Style Profile",
    "upload.confirm.ready": "Ready",
    "upload.confirm.notReady": "Not provided",
    "upload.confirm.optional": "Optional",
    "upload.confirm.start": "Start Now",
    "upload.confirm.cancel": "Cancel",
    "upload.confirm.bottomNotice": "AI will auto-generate bottom if not provided",
    "upload.confirm.qualityNotice": "Results may vary depending on the quality and conditions of uploaded photos",
    "upload.confirm.dashboardNotice": "After completion, you can view the results again in your Dashboard",
    "upload.confirm.accuracyTitle": "Tips for better accuracy",
    "upload.confirm.topAccuracyTip": "Photos with only the top (no bottom visible) give the best results",
    "upload.confirm.bottomAccuracyTip": "Photos with only the bottom (no top visible) give the best results",
    "upload.example": "Example",
    
    // Upload Validation
    "upload.validation.garmentPhotoType": "Please select a garment photo type",
    "upload.validation.runMode": "Please select a fitting mode",
    
    // Upload Mode Selection
    "upload.mode.title": "Select Try-On Mode",
    "upload.mode.top": "Top Fitting",
    "upload.mode.topDesc": "Keep your current bottom",
    "upload.mode.bottom": "Bottom Fitting",
    "upload.mode.bottomDesc": "Keep your current top",
    "upload.mode.full": "Full Outfit",
    "upload.mode.fullDesc": "Change both top + bottom",
    "upload.mode.fullDescSingle": "Single outfit photo fitting",
    "upload.mode.dressNotice": "For dresses and one-pieces, please use 'Full Outfit' mode.",
    "upload.mode.fullWarning": "⚠️ Full Outfit mode copies the entire outfit (top+bottom) from the photo. E.g., T-shirt + shorts photo → result also shows T-shirt + shorts. To change only the top, select 'Top Fitting'.",
    "upload.mode.credit": "credit",
    
    // Full Mode Sub-selection
    "upload.fullMode.typeTitle": "How to upload outfit",
    "upload.fullMode.separate": "Top & Bottom Separate",
    "upload.fullMode.separateDesc": "2 separate photos",
    "upload.fullMode.single": "Single Outfit Photo",
    "upload.fullMode.singleDesc": "1 photo with both items",
    
    // Outfit upload
    "upload.outfit.label": "Full Outfit Photo",
    "upload.outfit.desc": "A photo showing both top and bottom together",
    "upload.outfit.req1": "Both top and bottom must be visible",
    "upload.outfit.req2": "Front view recommended",
    "upload.outfitRequired": "Full outfit photo is required",
    
    // Mode-specific Person Photo Guidelines
    "upload.person.guide.top": "Upper body photo is enough! As long as your waist line is clearly visible, it will work naturally. (Full body photo is also fine.)",
    "upload.person.guide.bottom": "You must use a photo showing from hips to feet (shoes). Your face doesn't need to show, but if the lower body line is cut off, the pants fit may look awkward.",
    "upload.person.guide.full": "A full-body photo from head to toe is required. For harmonious silhouette of top and bottom, full body framing is most accurate.",
    
    // Common Person Photo Guidelines
    "upload.person.commonGuide.title": "Common Photo Tips",
    "upload.person.commonGuide.pose": "Pose: Spread arms slightly to the side, not against your body (A-Pose)",
    "upload.person.commonGuide.attire": "Attire: Loose or thick clothing (like puffer jackets) may cause inaccurate fitting results due to body shape detection issues",
    "upload.person.commonGuide.angle": "Angle: Face the camera directly, shoot horizontally",
    
    // Garment Photo Guidelines based on type
    "upload.garment.flatLay.main": "Clean photos showing only the garment work best.",
    "upload.garment.flatLay.tip1": "Photo laid flat on the floor",
    "upload.garment.flatLay.tip2": "No other objects or fingers in the background",
    "upload.garment.flatLay.tip3": "Smooth out wrinkles as much as possible",
    "upload.garment.model.main": "Photos of other models wearing the clothes also work!",
    "upload.garment.model.tip1": "Photos where garment shape is clearly visible (bags/hands/hair not covering the clothing)",
    "upload.garment.model.tip2": "Simple poses (twisted poses may cause poor results)",
    
    // Style Profile
    "profile.title": "Style Profile",
    "profile.subtitle": "Enter info for more accurate style analysis",
    "profile.gender.label": "Gender",
    "profile.gender.male": "Male",
    "profile.gender.female": "Female",
    "profile.gender.other": "Other",
    "profile.height": "Height",
    "profile.heightPlaceholder": "e.g., 170cm or 5'7\"",
    "profile.multiSelect": "Select multiple",
    "profile.other": "Other",
    "profile.otherPlaceholder": "Please specify...",
    "profile.bodyType.label": "Body Type",
    "profile.bodyType.upperHeavy": "Top Heavy",
    "profile.bodyType.lowerHeavy": "Bottom Heavy",
    "profile.bodyType.wideShoulders": "Wide Shoulders",
    "profile.bodyType.narrowShoulders": "Narrow Shoulders",
    "profile.bodyType.straight": "Straight/Rectangle",
    "profile.bodyType.slim": "Slim/Petite",
    "profile.occasion.label": "Occasion (TPO)",
    "profile.occasion.daily": "Daily",
    "profile.occasion.date": "Date",
    "profile.occasion.work": "Work",
    "profile.occasion.interview": "Interview",
    "profile.occasion.event": "Event",
    "profile.occasion.travel": "Travel",
    "profile.style.label": "Preferred Style",
    "profile.style.minimal": "Minimal",
    "profile.style.casual": "Casual",
    "profile.style.street": "Street",
    "profile.style.formal": "Formal",
    "profile.style.romantic": "Romantic",
    "profile.style.vintage": "Vintage",
    "profile.concerns.label": "Fashion Goals",
    "profile.concerns.placeholder": "e.g., I want my legs to look longer, I want to balance my shoulders...",
    "profile.reportNotice": "Style reports can only be viewed on this result screen and cannot be accessed again from the dashboard.",
    
    // Country Selection
    "profile.country.label": "Preferred Country/Region",
    "profile.country.hint": "Get analysis based on trending styles, celebrities, and brands from that country",
    "profile.country.placeholder": "e.g., USA, Korea, Japan...",
    
    // Fitting Options
    "profile.fittingOptions.title": "Fitting Options",
    "profile.fittingOptions.subtitle": "Choose fitting quality and garment photo type",
    "profile.runMode.label": "Fitting Mode",
    "profile.runMode.performance": "Quick Fitting",
    "profile.runMode.performanceDesc": "Recommended for simple t-shirts or basic designs",
    "profile.runMode.quality": "Precise Fitting",
    "profile.runMode.qualityDesc": "Recommended for complex patterns or high-quality results",
    "profile.garmentType.label": "Garment Photo Type",
    "profile.garmentType.flatLay": "Garment Only Photo",
    "profile.garmentType.flatLayDesc": "Hanger photo or background-removed image",
    "profile.garmentType.model": "Model Wearing Photo",
    "profile.garmentType.modelDesc": "When you want to extract clothes from shopping mall models or editorial photos",
    
    // Result
    "result.title": "Virtual Try-On Result",
    "result.processing": "AI is working on your look",
    "result.wait": "This takes about 30 seconds",
    "result.waitFull": "Full outfit mode takes about 1 minute",
    "result.progress.top": "Trying on the top...",
    "result.progress.bottom": "Matching the bottom...",
    "result.complete": "Try-On Complete!",
    "result.download": "Download",
    "result.share": "Share",
    "result.retry": "Try Again",
    "result.new": "Create New",
    "result.error": "Something went wrong",
    "result.errorGuide": "Please capture this error screen and contact us for credit compensation or refund.",
    "result.contactUs": "Contact Us",
    "result.imageTab": "Try-On Image",
    "result.reportTab": "Style Report",
    "result.estimatedTime": "Est. time: 10~20 sec",
    "result.estimatedTimeFull": "Est. time: 25~35 sec",
    "result.stepLabel": " step",
    "result.leaveWarningNotice": "Leaving the page may result in losing your results.",
    "result.reportDashboardNotice": "Style reports can only be viewed on this screen. Take a screenshot as you won't be able to access it from the dashboard!",
    
    // Style Report
    "report.title": "Style Analysis Report",
    "report.subtitle": "AI-analyzed outfit assessment",
    "report.celebrityMatch": "Celebrity Style Match",
    "report.brandCuration": "Recommended Brands",
    "report.actionPlan": "Style Action Plan",
    "report.fittingGuide": "Fitting Guide",
    "report.styleTags": "Style Tags",
    "report.analyzing": "AI is analyzing your style...",
    "report.noData": "Failed to load analysis results",
    
    // Share Reward
    "share.earnCredits": "Share & Get Credits!",
    "share.earnCreditsDesc": "Share with friends and get 1 free credit",
    "share.rewardComplete": "Reward Complete!",
    "share.rewardCompleteDesc": "1 credit has been added to your account",
    "share.clicks": "Clicks",
    "share.clicksRemaining": "{n} more clicks to earn reward!",
    "share.creditEarned": "+1 Credit Earned!",
    "share.creating": "Creating link...",
    "share.createLink": "Create Share Link",
    "share.linkCopied": "Link copied!",
    "share.textCopied": "Share text copied!",
    "share.refreshed": "Status updated!",
    "share.copyText": "Copy Text",
    "share.checkStatus": "Check Status",
    "share.instruction1": "Share on Instagram Stories with your image",
    "share.instruction2": "Make sure to include the link",
    "share.instruction3": "Get 1 free credit when 3 people click!",
    "share.shareTemplate": "I tried virtual fitting with TruPick! How do I look?\n\nTry it now\n{url}",
    
    // Share Page
    "share.loading": "Loading...",
    "share.title": "Welcome to TruPick!",
    "share.subtitle": "Try on clothes virtually before buying online",
    "share.alreadyVisited": "You've already visited!",
    "share.tryNow": "Try Now",
    "share.freeCredits": "Free try-on on signup",
    "share.errorTitle": "Link Not Found",
    "share.errorSubtitle": "This link is invalid or has expired",
    "share.goHome": "Go Home",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    // 1. 저장된 언어 설정 확인
    const saved = localStorage.getItem("language");
    if (saved === "ko" || saved === "en") {
      return saved;
    }
    // 2. 브라우저/폰 언어 설정 사용
    const browserLang = navigator.language.toLowerCase();
    return browserLang.startsWith("ko") ? "ko" : "en";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("language", lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.ko] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
