import { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "ko" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  ko: {
    // Navigation
    "nav.mypage": "마이페이지",
    "nav.dashboard": "대시보드",
    "nav.login": "로그인",
    
    // Auth
    "auth.badge": "스마트한 패션 시작",
    "auth.title": "FitVision 시작하기",
    "auth.subtitle": "Google 계정으로 간편하게 로그인하세요",
    "auth.google": "Google로 계속하기",
    "auth.benefits.title": "로그인하면 이런 혜택이!",
    "auth.benefits.1": "무료 이용권 5개 즉시 지급",
    "auth.benefits.2": "모든 결과물 저장 및 관리",
    "auth.benefits.3": "맞춤형 스타일 분석 리포트",
    "auth.terms": "로그인 시 서비스 이용약관에 동의하게 됩니다",
    
    // Dashboard
    "dashboard.welcome": "안녕하세요",
    "dashboard.subtitle": "오늘도 멋진 스타일을 만들어보세요",
    "dashboard.credits": "보유 이용권",
    "dashboard.buyCredits": "이용권 충전",
    "dashboard.totalUsage": "총 이용 횟수",
    "dashboard.usageDesc": "지금까지 생성한 피팅 이미지",
    "dashboard.newTryon": "새로운 피팅",
    "dashboard.startNow": "지금 바로 시작하세요",
    "dashboard.createNew": "새로 만들기",
    "dashboard.history": "이용 내역",
    "dashboard.noHistory": "아직 이용 내역이 없습니다",
    "dashboard.createFirst": "첫 피팅 만들기",
    "dashboard.tryonAction": "가상 피팅",
    "dashboard.purchaseAction": "이용권 구매",
    "dashboard.credit": "이용권",
    "dashboard.view": "보기",
    
    // MyPage
    "mypage.title": "마이페이지",
    "mypage.subtitle": "프로필 관리 및 이용권 충전",
    "mypage.profile": "내 프로필",
    "mypage.currentCredits": "보유 이용권",
    "mypage.memberSince": "가입일",
    "mypage.buyCredits": "이용권 충전",
    "mypage.buyCreditsDesc": "이용권을 충전하여 더 많은 가상 피팅을 즐겨보세요",
    "mypage.credits": "이용권",
    "mypage.popular": "인기",
    "mypage.purchase": "구매하기",
    "mypage.paymentNote": "PayPal로 안전하게 결제됩니다",
    
    // Promo Codes
    "promo.title": "프로모션 코드",
    "promo.searchPlaceholder": "프로모션 코드 입력",
    "promo.searchLabel": "프로모션 코드 검색",
    "promo.notFound": "유효하지 않은 프로모션 코드입니다",
    "promo.claim": "받기",
    "promo.use": "사용하기",
    "promo.applied": "적용됨",
    "promo.discount": "할인",
    "promo.creditsBonus": "이용권 추가",
    "promo.myPromoCodes": "보유 프로모션",
    "promo.noPromoCodes": "보유한 프로모션이 없습니다",
    "promo.searchHint": "프로모션 코드를 검색해보세요",
    "promo.selectDiscount": "할인 쿠폰 선택",
    
    // Purchase Flow
    "purchase.promoStep": "프로모션 선택",
    "purchase.packageStep": "이용권 선택",
    "purchase.paymentStep": "결제",
    "purchase.skip": "다음",
    "purchase.next": "다음",
    "purchase.back": "이전",
    "purchase.summary": "주문 내역",
    "purchase.total": "결제 금액",
    "purchase.pay": "결제하기",
    "purchase.lemonSqueezyNote": "결제 완료 후 크레딧이 자동으로 충전됩니다.",
    "purchase.redirecting": "결제 페이지로 이동합니다...",
    "purchase.processing": "결제 처리 중",
    "purchase.success": "결제가 완료되었습니다!",
    "purchase.error": "결제 처리에 실패했습니다",
    
    // Upload - No Credits
    "upload.noCredits.title": "이용권이 없습니다",
    "upload.noCredits.description": "피팅 분석을 시작하려면 이용권이 필요합니다. 이용권을 구매해주세요.",
    "upload.noCredits.cancel": "취소",
    "upload.noCredits.purchase": "이용권 구매하기",
    
    // Landing
    "hero.badge": "AI 가상 피팅 + 스타일 분석",
    "hero.title1": "옷을 입어보지 않아도",
    "hero.title2": "내 모습을 확인하세요",
    "hero.subtitle": "미리 입어보고, 실패 없이 구매하세요.",
    "hero.cta": "시작하기",
    "feature.speed": "30초 만에 완성",
    "feature.face": "얼굴 그대로 유지",
    "feature.report": "스타일 분석 리포트",
    "benefits.title": "이런 분들을 위해 만들었어요",
    "benefits.subtitle": "가상 피팅 + 스타일 코칭으로 더 스마트한 패션 라이프",
    "benefits.1": "온라인 쇼핑 전 가상 피팅",
    "benefits.2": "내 체형에 맞는 옷인지 확인",
    "benefits.3": "TPO에 맞는 코디 점검",
    "benefits.4": "개인 맞춤 스타일 조언",
    "howto.title": "어떻게 사용하나요?",
    "howto.subtitle": "4단계로 가상 피팅 + 스타일 분석 완성",
    "howto.step1.title": "전신 사진 업로드",
    "howto.step1.desc": "정면을 바라보는 전신 사진을 올려주세요",
    "howto.step2.title": "옷 사진 선택",
    "howto.step2.desc": "입어보고 싶은 상의, 하의 이미지를 추가하세요",
    "howto.step3.title": "스타일 정보 입력",
    "howto.step3.desc": "체형, TPO, 선호 스타일, 패션 고민을 입력하세요",
    "howto.step4.title": "결과 확인",
    "howto.step4.desc": "가상 피팅 이미지 + 스타일 분석 리포트를 받아보세요",
    "cta.title": "지금 바로 체험해보세요",
    "cta.subtitle": "회원가입 없이 바로 시작",
    "cta.button": "무료로 시작하기",
    "footer.copyright": "© 2024 Trukin. All rights reserved.",
    "footer.privacy": "개인정보처리방침",
    "footer.terms": "이용약관",
    "footer.refund": "환불정책",
    "footer.companyInfo": "Trukin | 대표자: 정예준 (Yejoon Jeong) | 이메일: admin@trukin.app",
    
    // Upload
    "upload.back": "돌아가기",
    "upload.title": "이미지 업로드",
    "upload.subtitle": "전신 사진과 입어보고 싶은 옷을 업로드하세요",
    "upload.person.label": "전신 사진",
    "upload.person.desc": "정면을 바라보는 전신 사진",
    "upload.person.req1": "정면 전신 (손이 보여야 함)",
    "upload.person.req2": "단체 사진 불가",
    "upload.person.req3": "측면/반신/앉은 자세 불가",
    "upload.person.req4": "물건을 들고 있으면 안됨",
    "upload.person.req5": "밝고 선명한 사진 권장",
    "upload.top.label": "상의",
    "upload.top.desc": "입어보고 싶은 상의 이미지",
    "upload.top.req1": "어떤 배경이든 OK! 편집 없이 바로 업로드",
    "upload.top.req2": "정면 촬영 권장 (뒷면 불가)",
    "upload.top.req3": "접히거나 구겨진 옷은 피해주세요",
    "upload.top.req4": "여러 벌 겹쳐진 사진 불가",
    "upload.top.req5": "",
    "upload.bottom.label": "하의",
    "upload.bottom.desc": "하의 없으면 AI가 자동 생성",
    "upload.bottom.descFull": "입어보고 싶은 하의 이미지",
    "upload.bottom.req1": "상의가 보이지 않는 하의만 담긴 사진이 가장 정확해요",
    "upload.bottom.req2": "정면 촬영 권장",
    "upload.optional": "선택",
    "upload.dropzone": "클릭하거나 드래그",
    "upload.format": "JPG, PNG, BMP (최대 5MB)",
    "upload.requirements": "이미지 요구사항",
    "upload.submit": "피팅 + 분석 시작하기",
    "upload.submitting": "처리 중...",
    "upload.required": "전신 사진과 상의는 필수입니다",
    "upload.fullModeRequired": "전신 모드에서는 상의와 하의 모두 필수입니다",
    "upload.confirm.title": "업로드 현황 확인",
    "upload.confirm.description": "업로드 항목을 확인하세요.",
    "upload.confirm.person": "전신 사진",
    "upload.confirm.top": "상의",
    "upload.confirm.bottom": "하의",
    "upload.confirm.outfit": "전체 코디 사진",
    "upload.confirm.profile": "스타일 프로필",
    "upload.confirm.ready": "준비 완료",
    "upload.confirm.notReady": "미입력",
    "upload.confirm.optional": "선택사항",
    "upload.confirm.start": "최종 시작하기",
    "upload.confirm.cancel": "취소",
    "upload.confirm.bottomNotice": "하의 미입력 시 AI가 자동으로 생성합니다",
    "upload.confirm.qualityNotice": "결과물은 업로드된 사진의 화질과 조건에 따라 달라질 수 있습니다",
    "upload.confirm.dashboardNotice": "분석 완료 후 대시보드에서 결과를 다시 확인할 수 있어요",
    "upload.confirm.accuracyTitle": "정확도 높이는 팁",
    "upload.confirm.topAccuracyTip": "하의가 보이지 않는 상의만 담긴 사진이 가장 정확해요",
    "upload.confirm.bottomAccuracyTip": "상의가 보이지 않는 하의만 담긴 사진이 가장 정확해요",
    "upload.example": "예시",
    
    // Upload Mode Selection
    "upload.mode.title": "피팅 모드 선택",
    "upload.mode.top": "상의만",
    "upload.mode.topDesc": "하의는 그대로 유지",
    "upload.mode.bottom": "하의만",
    "upload.mode.bottomDesc": "상의는 그대로 유지",
    "upload.mode.full": "전체 코디",
    "upload.mode.fullDesc": "상의 + 하의 모두 교체",
    "upload.mode.credit": "이용권",
    
    // Full Mode Sub-selection
    "upload.fullMode.typeTitle": "옷 사진 업로드 방식",
    "upload.fullMode.separate": "상의 / 하의 따로",
    "upload.fullMode.separateDesc": "서로 다른 상의, 하의 2장",
    "upload.fullMode.single": "한 장에 전체 코디",
    "upload.fullMode.singleDesc": "상하의가 함께 있는 1장",
    
    // Outfit upload
    "upload.outfit.label": "전체 코디 사진",
    "upload.outfit.desc": "상의와 하의가 함께 보이는 옷 사진",
    "upload.outfit.req1": "상의와 하의가 모두 보여야 해요",
    "upload.outfit.req2": "정면 촬영 권장",
    "upload.outfitRequired": "전체 코디 사진이 필요합니다",
    
    // Style Profile
    "profile.title": "스타일 프로필",
    "profile.subtitle": "더 정확한 스타일 분석을 위해 정보를 입력해주세요",
    "profile.height": "키",
    "profile.heightPlaceholder": "예: 170cm",
    "profile.multiSelect": "복수 선택 가능",
    "profile.other": "기타",
    "profile.otherPlaceholder": "직접 입력해주세요...",
    "profile.bodyType.label": "체형",
    "profile.bodyType.upperHeavy": "상체 통통",
    "profile.bodyType.lowerHeavy": "하체 통통",
    "profile.bodyType.wideShoulders": "어깨 넓음",
    "profile.bodyType.narrowShoulders": "어깨 좁음",
    "profile.bodyType.straight": "일자형",
    "profile.bodyType.slim": "마른 체형",
    "profile.occasion.label": "착용 목적 (TPO)",
    "profile.occasion.daily": "데일리",
    "profile.occasion.date": "데이트",
    "profile.occasion.work": "출근",
    "profile.occasion.interview": "면접",
    "profile.occasion.event": "행사",
    "profile.occasion.travel": "여행",
    "profile.style.label": "선호 스타일",
    "profile.style.minimal": "미니멀",
    "profile.style.casual": "캐주얼",
    "profile.style.street": "스트릿",
    "profile.style.formal": "포멀",
    "profile.style.romantic": "로맨틱",
    "profile.style.vintage": "빈티지",
    "profile.concerns.label": "패션 고민 / 목표",
    "profile.concerns.placeholder": "예: 다리가 길어 보이면 좋겠어요, 어깨가 좁아 보이게 하고 싶어요...",
    
    // Result
    "result.title": "가상 피팅 결과",
    "result.processing": "AI가 열심히 작업 중이에요",
    "result.wait": "약 30초 정도 소요됩니다",
    "result.waitFull": "전체 코디 모드는 약 1분 정도 소요됩니다",
    "result.progress.top": "상의를 입어보는 중...",
    "result.progress.bottom": "하의를 매칭하는 중...",
    "result.complete": "피팅 완료!",
    "result.download": "다운로드",
    "result.share": "공유하기",
    "result.retry": "다시 시도",
    "result.new": "새로 만들기",
    "result.error": "오류가 발생했습니다",
    "result.imageTab": "피팅 이미지",
    "result.reportTab": "스타일 리포트",
    "result.estimatedTime": "예상 소요: 30~60초",
    "result.estimatedTimeFull": "예상 소요: 1~2분",
    "result.stepLabel": "단계",
    
    // Style Report
    "report.title": "스타일 분석 리포트",
    "report.subtitle": "AI가 분석한 당신의 코디",
    "report.overallScore": "전체 코디 점수",
    "report.scores": "세부 점수",
    "report.fitScore": "체형 적합도",
    "report.colorScore": "색상 조화",
    "report.balanceScore": "밸런스/비율",
    "report.occasionScore": "상황 적합성",
    "report.fitAnalysis": "체형 기반 핏 분석",
    "report.fitTip1": "상의가 체형을 자연스럽게 보완해줍니다",
    "report.fitTip2": "실루엣이 전체적으로 균형있어 보입니다",
    "report.fitTip3": "길이와 핏이 비율에 잘 맞습니다",
    "report.colorAnalysis": "색 조합·톤 분석",
    "report.colorTip1": "색상 대비가 자연스럽습니다",
    "report.colorTip2": "상하의 조화가 잘 이루어집니다",
    "report.tpoAnalysis": "TPO(상황) 적합성",
    "report.tpoTip": "선택하신 상황에 적합한 스타일입니다. 전체적인 분위기가 목적에 잘 맞습니다.",
    "report.personalGoals": "개인 맞춤 솔루션",
    "report.goalTip": "입력하신 고민에 맞는 스타일 팁을 제공드립니다. 하이웨스트 하의와 상의 프론트 인으로 비율을 개선할 수 있습니다.",
    "report.styleTags": "스타일 태그",
    
    // Share Reward
    "share.earnCredits": "공유하고 이용권 받기!",
    "share.earnCreditsDesc": "친구들에게 공유하면 무료 이용권 1개를 드려요",
    "share.rewardComplete": "보상 지급 완료!",
    "share.rewardCompleteDesc": "이용권 1개가 지급되었어요",
    "share.clicks": "클릭 수",
    "share.clicksRemaining": "{n}번 더 클릭되면 보상 지급!",
    "share.creditEarned": "+1 이용권 획득!",
    "share.creating": "링크 생성 중...",
    "share.createLink": "공유 링크 만들기",
    "share.linkCopied": "링크가 복사되었어요",
    "share.textCopied": "공유 텍스트가 복사되었어요",
    "share.refreshed": "상태가 업데이트되었어요",
    "share.copyText": "텍스트 복사",
    "share.checkStatus": "상태 확인",
    "share.instruction1": "인스타그램 스토리에 이미지와 함께 공유하세요",
    "share.instruction2": "링크를 꼭 포함해주세요",
    "share.instruction3": "3명이 클릭하면 이용권 1개 자동 지급!",
    "share.shareTemplate": "FitVision으로 가상 피팅해봤어요! 내 모습이 어때 보여?\n\n지금 바로 체험하기\n{url}",
    
    // Share Page
    "share.loading": "로딩 중...",
    "share.title": "FitVision에 오신 것을 환영해요!",
    "share.subtitle": "AI 가상 피팅으로 온라인 쇼핑 전 미리 입어보세요",
    "share.alreadyVisited": "이미 방문하셨네요!",
    "share.tryNow": "지금 바로 체험하기",
    "share.freeCredits": "가입 시 무료 이용권 5개 제공",
    "share.errorTitle": "링크를 찾을 수 없어요",
    "share.errorSubtitle": "유효하지 않거나 만료된 링크예요",
    "share.goHome": "홈으로 가기",
  },
  en: {
    // Navigation
    "nav.mypage": "My Page",
    "nav.dashboard": "Dashboard",
    "nav.login": "Login",
    
    // Auth
    "auth.badge": "Smart Fashion Starts Here",
    "auth.title": "Get Started with FitVision",
    "auth.subtitle": "Sign in easily with your Google account",
    "auth.google": "Continue with Google",
    "auth.benefits.title": "Benefits of signing in",
    "auth.benefits.1": "5 free credits instantly",
    "auth.benefits.2": "Save and manage all results",
    "auth.benefits.3": "Personalized style analysis reports",
    "auth.terms": "By signing in, you agree to our Terms of Service",
    
    // Dashboard
    "dashboard.welcome": "Hello",
    "dashboard.subtitle": "Create amazing styles today",
    "dashboard.credits": "Credits",
    "dashboard.buyCredits": "Buy Credits",
    "dashboard.totalUsage": "Total Usage",
    "dashboard.usageDesc": "Try-on images created so far",
    "dashboard.newTryon": "New Try-On",
    "dashboard.startNow": "Start right now",
    "dashboard.createNew": "Create New",
    "dashboard.history": "Usage History",
    "dashboard.noHistory": "No usage history yet",
    "dashboard.createFirst": "Create your first try-on",
    "dashboard.tryonAction": "Virtual Try-On",
    "dashboard.purchaseAction": "Credit Purchase",
    "dashboard.credit": "credit",
    "dashboard.view": "View",
    
    // MyPage
    "mypage.title": "My Page",
    "mypage.subtitle": "Manage profile and buy credits",
    "mypage.profile": "My Profile",
    "mypage.currentCredits": "Current Credits",
    "mypage.memberSince": "Member Since",
    "mypage.buyCredits": "Buy Credits",
    "mypage.buyCreditsDesc": "Purchase credits to enjoy more virtual try-ons",
    "mypage.credits": "credits",
    "mypage.popular": "Popular",
    "mypage.purchase": "Purchase",
    "mypage.paymentNote": "Secure payment via PayPal",
    
    // Promo Codes
    "promo.title": "Promo Codes",
    "promo.searchPlaceholder": "Enter promo code",
    "promo.searchLabel": "Search promo code",
    "promo.notFound": "Invalid promo code",
    "promo.claim": "Claim",
    "promo.use": "Use",
    "promo.applied": "applied",
    "promo.discount": "off",
    "promo.creditsBonus": "credits bonus",
    "promo.myPromoCodes": "My Promo Codes",
    "promo.noPromoCodes": "No promo codes yet",
    "promo.searchHint": "Search for promo codes",
    "promo.selectDiscount": "Select discount coupon",
    
    // Purchase Flow
    "purchase.promoStep": "Select Promo",
    "purchase.packageStep": "Select Package",
    "purchase.paymentStep": "Payment",
    "purchase.skip": "Skip",
    "purchase.next": "Next",
    "purchase.back": "Back",
    "purchase.summary": "Order Summary",
    "purchase.total": "Total",
    "purchase.pay": "Pay Now",
    "purchase.lemonSqueezyNote": "Credits will be automatically added after payment.",
    "purchase.redirecting": "Redirecting to payment page...",
    "purchase.processing": "Processing payment",
    "purchase.success": "Payment completed!",
    "purchase.error": "Payment failed",
    
    // Upload - No Credits
    "upload.noCredits.title": "No Credits Available",
    "upload.noCredits.description": "You need credits to start a try-on analysis. Please purchase credits.",
    "upload.noCredits.cancel": "Cancel",
    "upload.noCredits.purchase": "Buy Credits",
    
    // Landing
    "hero.badge": "AI Virtual Try-On + Style Analysis",
    "hero.title1": "See yourself in any outfit",
    "hero.title2": "without trying it on",
    "hero.subtitle": "Try First, Buy Better.",
    "hero.cta": "Get Started",
    "feature.speed": "Done in 30 seconds",
    "feature.face": "Keep your real face",
    "feature.report": "Style Analysis Report",
    "benefits.title": "Perfect for you",
    "benefits.subtitle": "Virtual fitting + style coaching for smarter fashion decisions",
    "benefits.1": "Try before you buy online",
    "benefits.2": "Check if clothes fit your body type",
    "benefits.3": "Verify outfit for the occasion",
    "benefits.4": "Get personalized style advice",
    "howto.title": "How does it work?",
    "howto.subtitle": "Virtual fitting + style analysis in 4 steps",
    "howto.step1.title": "Upload your photo",
    "howto.step1.desc": "A front-facing full-body photo works best",
    "howto.step2.title": "Choose your outfit",
    "howto.step2.desc": "Add the top and bottom images you want to try",
    "howto.step3.title": "Enter style info",
    "howto.step3.desc": "Body type, occasion, preferred style, fashion goals",
    "howto.step4.title": "Get your result",
    "howto.step4.desc": "Receive try-on image + style analysis report",
    "cta.title": "Try it now",
    "cta.subtitle": "No sign up required",
    "cta.button": "Start Free",
    "footer.copyright": "© 2024 Trukin. All rights reserved.",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",
    "footer.refund": "Refund Policy",
    "footer.companyInfo": "Trukin | Owner: Yejoon Jeong | Email: admin@trukin.app",
    
    // Upload
    "upload.back": "Back",
    "upload.title": "Upload Images",
    "upload.subtitle": "Upload your photo and the clothes you want to try",
    "upload.person.label": "Your Photo",
    "upload.person.desc": "Front-facing full-body photo",
    "upload.person.req1": "Full body, front view (hands visible)",
    "upload.person.req2": "No group photos",
    "upload.person.req3": "No side/half body/sitting poses",
    "upload.person.req4": "Don't hold any objects",
    "upload.person.req5": "Bright and clear photo recommended",
    "upload.top.label": "Top",
    "upload.top.desc": "The top you want to try on",
    "upload.top.req1": "Any background OK! Upload directly without editing",
    "upload.top.req2": "Front view recommended (no back)",
    "upload.top.req3": "Avoid folded or wrinkled clothes",
    "upload.top.req4": "No multiple layered items",
    "upload.top.req5": "",
    "upload.bottom.label": "Bottom",
    "upload.bottom.desc": "AI will generate if not provided",
    "upload.bottom.descFull": "The bottom you want to try on",
    "upload.bottom.req1": "Photos with only bottoms (no top visible) give the best accuracy",
    "upload.bottom.req2": "Front view recommended",
    "upload.optional": "Optional",
    "upload.dropzone": "Click or drag to upload",
    "upload.format": "JPG, PNG, BMP (max 5MB)",
    "upload.requirements": "Image Requirements",
    "upload.submit": "Generate Try-On + Analysis",
    "upload.submitting": "Processing...",
    "upload.required": "Photo and top are required",
    "upload.fullModeRequired": "Both top and bottom are required for full outfit mode",
    "upload.confirm.title": "Upload Summary",
    "upload.confirm.description": "Please review your uploads.",
    "upload.confirm.person": "Full Body Photo",
    "upload.confirm.top": "Top",
    "upload.confirm.bottom": "Bottom",
    "upload.confirm.outfit": "Full Outfit Photo",
    "upload.confirm.profile": "Style Profile",
    "upload.confirm.ready": "Ready",
    "upload.confirm.notReady": "Not provided",
    "upload.confirm.optional": "Optional",
    "upload.confirm.start": "Start Now",
    "upload.confirm.cancel": "Cancel",
    "upload.confirm.bottomNotice": "AI will auto-generate bottom if not provided",
    "upload.confirm.qualityNotice": "Results may vary depending on the quality and conditions of uploaded photos",
    "upload.confirm.dashboardNotice": "After completion, you can view the results again in your Dashboard",
    "upload.confirm.accuracyTitle": "Tips for better accuracy",
    "upload.confirm.topAccuracyTip": "Photos with only the top (no bottom visible) give the best results",
    "upload.confirm.bottomAccuracyTip": "Photos with only the bottom (no top visible) give the best results",
    "upload.example": "Example",
    
    // Upload Mode Selection
    "upload.mode.title": "Select Try-On Mode",
    "upload.mode.top": "Top Only",
    "upload.mode.topDesc": "Keep your current bottom",
    "upload.mode.bottom": "Bottom Only",
    "upload.mode.bottomDesc": "Keep your current top",
    "upload.mode.full": "Full Outfit",
    "upload.mode.fullDesc": "Change both top + bottom",
    "upload.mode.credit": "credit",
    
    // Full Mode Sub-selection
    "upload.fullMode.typeTitle": "How to upload outfit",
    "upload.fullMode.separate": "Top & Bottom Separate",
    "upload.fullMode.separateDesc": "2 separate photos",
    "upload.fullMode.single": "Single Outfit Photo",
    "upload.fullMode.singleDesc": "1 photo with both items",
    
    // Outfit upload
    "upload.outfit.label": "Full Outfit Photo",
    "upload.outfit.desc": "A photo showing both top and bottom together",
    "upload.outfit.req1": "Both top and bottom must be visible",
    "upload.outfit.req2": "Front view recommended",
    "upload.outfitRequired": "Full outfit photo is required",
    
    // Style Profile
    "profile.title": "Style Profile",
    "profile.subtitle": "Enter info for more accurate style analysis",
    "profile.height": "Height",
    "profile.heightPlaceholder": "e.g., 170cm or 5'7\"",
    "profile.multiSelect": "Select multiple",
    "profile.other": "Other",
    "profile.otherPlaceholder": "Please specify...",
    "profile.bodyType.label": "Body Type",
    "profile.bodyType.upperHeavy": "Top Heavy",
    "profile.bodyType.lowerHeavy": "Bottom Heavy",
    "profile.bodyType.wideShoulders": "Wide Shoulders",
    "profile.bodyType.narrowShoulders": "Narrow Shoulders",
    "profile.bodyType.straight": "Straight/Rectangle",
    "profile.bodyType.slim": "Slim/Petite",
    "profile.occasion.label": "Occasion (TPO)",
    "profile.occasion.daily": "Daily",
    "profile.occasion.date": "Date",
    "profile.occasion.work": "Work",
    "profile.occasion.interview": "Interview",
    "profile.occasion.event": "Event",
    "profile.occasion.travel": "Travel",
    "profile.style.label": "Preferred Style",
    "profile.style.minimal": "Minimal",
    "profile.style.casual": "Casual",
    "profile.style.street": "Street",
    "profile.style.formal": "Formal",
    "profile.style.romantic": "Romantic",
    "profile.style.vintage": "Vintage",
    "profile.concerns.label": "Fashion Goals",
    "profile.concerns.placeholder": "e.g., I want my legs to look longer, I want to balance my shoulders...",
    
    // Result
    "result.title": "Virtual Try-On Result",
    "result.processing": "AI is working on your look",
    "result.wait": "This takes about 30 seconds",
    "result.waitFull": "Full outfit mode takes about 1 minute",
    "result.progress.top": "Trying on the top...",
    "result.progress.bottom": "Matching the bottom...",
    "result.complete": "Try-On Complete!",
    "result.download": "Download",
    "result.share": "Share",
    "result.retry": "Try Again",
    "result.new": "Create New",
    "result.error": "Something went wrong",
    "result.imageTab": "Try-On Image",
    "result.reportTab": "Style Report",
    "result.estimatedTime": "Est. time: 30~60 sec",
    "result.estimatedTimeFull": "Est. time: 1~2 min",
    "result.stepLabel": " step",
    
    // Style Report
    "report.title": "Style Analysis Report",
    "report.subtitle": "AI-analyzed outfit assessment",
    "report.overallScore": "Overall Outfit Score",
    "report.scores": "Detailed Scores",
    "report.fitScore": "Body Fit",
    "report.colorScore": "Color Harmony",
    "report.balanceScore": "Balance/Proportion",
    "report.occasionScore": "Occasion Match",
    "report.fitAnalysis": "Body-Based Fit Analysis",
    "report.fitTip1": "The top naturally complements your body type",
    "report.fitTip2": "The overall silhouette looks well-balanced",
    "report.fitTip3": "Length and fit work well with your proportions",
    "report.colorAnalysis": "Color & Tone Analysis",
    "report.colorTip1": "Color contrast looks natural",
    "report.colorTip2": "Top and bottom harmonize well",
    "report.tpoAnalysis": "Occasion Suitability",
    "report.tpoTip": "This style suits your selected occasion. The overall vibe matches the purpose well.",
    "report.personalGoals": "Personalized Solutions",
    "report.goalTip": "Based on your goals: High-waisted bottoms with a front-tucked top can improve proportions.",
    "report.styleTags": "Style Tags",
    
    // Share Reward
    "share.earnCredits": "Share & Get Credits!",
    "share.earnCreditsDesc": "Share with friends and get 1 free credit",
    "share.rewardComplete": "Reward Complete!",
    "share.rewardCompleteDesc": "1 credit has been added to your account",
    "share.clicks": "Clicks",
    "share.clicksRemaining": "{n} more clicks to earn reward!",
    "share.creditEarned": "+1 Credit Earned!",
    "share.creating": "Creating link...",
    "share.createLink": "Create Share Link",
    "share.linkCopied": "Link copied!",
    "share.textCopied": "Share text copied!",
    "share.refreshed": "Status updated!",
    "share.copyText": "Copy Text",
    "share.checkStatus": "Check Status",
    "share.instruction1": "Share on Instagram Stories with your image",
    "share.instruction2": "Make sure to include the link",
    "share.instruction3": "Get 1 free credit when 3 people click!",
    "share.shareTemplate": "I tried virtual fitting with FitVision! How do I look?\n\nTry it now\n{url}",
    
    // Share Page
    "share.loading": "Loading...",
    "share.title": "Welcome to FitVision!",
    "share.subtitle": "Try on clothes virtually before buying online",
    "share.alreadyVisited": "You've already visited!",
    "share.tryNow": "Try Now",
    "share.freeCredits": "Get 5 free credits on signup",
    "share.errorTitle": "Link Not Found",
    "share.errorSubtitle": "This link is invalid or has expired",
    "share.goHome": "Go Home",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    // 1. 저장된 언어 설정 확인
    const saved = localStorage.getItem("language");
    if (saved === "ko" || saved === "en") {
      return saved;
    }
    // 2. 브라우저/폰 언어 설정 사용
    const browserLang = navigator.language.toLowerCase();
    return browserLang.startsWith("ko") ? "ko" : "en";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("language", lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.ko] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
