import { useEffect, useState } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from "@/components/ui/dialog";
import { ScrollArea } from "@/components/ui/scroll-area";
import { useLanguage } from "@/contexts/LanguageContext";
import { useAuth } from "@/hooks/useAuth";
import LanguageSwitch from "@/components/LanguageSwitch";
import Logo from "@/components/Logo";
import { Sparkles, FileText, Shield, Check } from "lucide-react";

const Auth = () => {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const { t, language } = useLanguage();
  const { user, loading, signInWithGoogle } = useAuth();
  
  // Mode: "login" or "signup"
  const [mode, setMode] = useState<"login" | "signup">(
    searchParams.get("mode") === "signup" ? "signup" : "login"
  );
  
  // Terms agreement states (only needed for signup)
  const [termsRead, setTermsRead] = useState(false);
  const [privacyRead, setPrivacyRead] = useState(false);
  
  // Dialog states
  const [termsDialogOpen, setTermsDialogOpen] = useState(false);
  const [privacyDialogOpen, setPrivacyDialogOpen] = useState(false);

  useEffect(() => {
    if (!loading && user) {
      navigate("/");
    }
  }, [user, loading, navigate]);

  const handleGoogleLogin = async () => {
    const { error } = await signInWithGoogle();
    if (error) {
      console.error("Login error:", error.message);
    }
  };

  const handleTermsAgree = () => {
    setTermsRead(true);
    setTermsDialogOpen(false);
  };

  const handlePrivacyAgree = () => {
    setPrivacyRead(true);
    setPrivacyDialogOpen(false);
  };

  const allAgreed = termsRead && privacyRead;
  const isSignup = mode === "signup";
  // Login mode: no terms required. Signup mode: terms required.
  const canProceed = isSignup ? allAgreed : true;

  if (loading) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <div className="animate-pulse text-muted-foreground">Loading...</div>
      </div>
    );
  }

  // Terms content
  const termsContent = language === "ko" ? (
    <div className="space-y-4 text-sm text-muted-foreground">
      <h4 className="font-semibold text-foreground">제1조 (목적)</h4>
      <p>이 약관은 Trukin(이하 "회사")이 제공하는 TruPick 서비스(이하 "서비스")의 이용과 관련하여 회사와 이용자 간의 권리, 의무 및 책임사항을 규정함을 목적으로 합니다.</p>
      <h4 className="font-semibold text-foreground">제2조 (정의)</h4>
      <p>"서비스"란 인공지능(AI) 기술을 활용한 가상 의류 피팅 및 스타일 분석 서비스를 의미합니다.</p>
      <h4 className="font-semibold text-foreground">제7조 (AI 생성물에 대한 면책)</h4>
      <p>1. 본 서비스에서 생성되는 이미지는 인공지능(AI) 기술을 통해 합성된 결과물이며, 실제 착용 시의 외관, 핏, 색상 등과 차이가 있을 수 있습니다.</p>
      <p>2. 회사는 AI 생성 이미지의 정확성, 완전성, 또는 특정 목적에의 적합성을 보증하지 않습니다.</p>
      <p>3. 회원은 본 서비스의 결과물을 참고 자료로만 활용해야 하며, 이를 기반으로 한 구매 결정 등에 대해 회사는 책임을 지지 않습니다.</p>
      <h4 className="font-semibold text-foreground">제8조 (워터마크 및 출처 표시)</h4>
      <p>1. 본 서비스에서 생성된 모든 이미지에는 AI 생성물임을 나타내는 워터마크("by TruPick AI")가 포함됩니다.</p>
      <p>2. 회원은 해당 워터마크를 제거, 변경, 또는 가리는 행위를 해서는 안 됩니다.</p>
      <p className="text-xs text-muted-foreground mt-6">전체 이용약관은 서비스 하단의 이용약관 링크에서 확인하실 수 있습니다.</p>
    </div>
  ) : (
    <div className="space-y-4 text-sm text-muted-foreground">
      <h4 className="font-semibold text-foreground">Article 1 (Purpose)</h4>
      <p>These Terms govern the rights, duties, and responsibilities between Trukin ("Company") and users in connection with the TruPick service ("Service").</p>
      <h4 className="font-semibold text-foreground">Article 2 (Definitions)</h4>
      <p>"Service" refers to virtual clothing try-on and style analysis services utilizing artificial intelligence (AI) technology.</p>
      <h4 className="font-semibold text-foreground">Article 7 (Disclaimer for AI-Generated Content)</h4>
      <p>1. Images generated by this Service are synthesized using AI technology and may differ from actual appearance, fit, or color when worn.</p>
      <p>2. The Company does not guarantee the accuracy, completeness, or fitness for any particular purpose of AI-generated images.</p>
      <p>3. Members should use the Service results as reference only; the Company is not responsible for purchase decisions based on these results.</p>
      <h4 className="font-semibold text-foreground">Article 8 (Watermark and Attribution)</h4>
      <p>1. All images generated by this Service include a watermark ("by TruPick AI") indicating AI-generated content.</p>
      <p>2. Members must not remove, alter, or obscure this watermark.</p>
      <p className="text-xs text-muted-foreground mt-6">Full Terms of Service can be found via the link at the bottom of the service.</p>
    </div>
  );

  const privacyContent = language === "ko" ? (
    <div className="space-y-4 text-sm text-muted-foreground">
      <h4 className="font-semibold text-foreground">제1조 (개인정보 처리 목적)</h4>
      <p>Trukin(이하 "회사")은 다음의 목적을 위하여 개인정보를 처리합니다. 처리하고 있는 개인정보는 다음의 목적 이외의 용도로는 이용되지 않으며, 이용 목적이 변경되는 경우에는 별도의 동의를 받는 등 필요한 조치를 이행할 예정입니다.</p>
      <h4 className="font-semibold text-foreground">제4조 (개인정보 제3자 제공)</h4>
      <p>회사는 이용자의 개인정보를 원칙적으로 외부에 제공하지 않습니다. 다만, 다음의 경우에는 예외로 합니다:</p>
      <p>• AI 기술 서비스 제공자: 회사는 가상 피팅 서비스 제공을 위해 AI 기술 파트너사와 이미지 데이터를 공유할 수 있습니다. 이 경우 이미지 데이터는 서비스 처리 목적으로만 사용되며, 처리 완료 후 즉시 삭제됩니다.</p>
      <h4 className="font-semibold text-foreground">제5조 (개인정보의 보유 및 이용 기간)</h4>
      <p>• 사진 이미지 파일(업로드 사진 및 결과 이미지): 서비스 처리 완료 후 72시간 이내 삭제</p>
      <p>• 가상 피팅 결과 이미지는 72시간 후 자동 만료되며, 영구 저장되지 않습니다.</p>
      <h4 className="font-semibold text-foreground">제10조 (개인정보 보호책임자)</h4>
      <p>성명: 정예준 (Yejoon Jeong)</p>
      <p>이메일: admin@trukin.app</p>
      <p className="text-xs text-muted-foreground mt-6">전체 개인정보처리방침은 서비스 하단의 링크에서 확인하실 수 있습니다.</p>
    </div>
  ) : (
    <div className="space-y-4 text-sm text-muted-foreground">
      <h4 className="font-semibold text-foreground">Article 1 (Purpose of Processing Personal Information)</h4>
      <p>Trukin ("Company") processes personal information for the following purposes. The personal information being processed will not be used for purposes other than the following, and if the purpose of use changes, necessary measures such as obtaining separate consent will be taken.</p>
      <h4 className="font-semibold text-foreground">Article 4 (Provision of Personal Information to Third Parties)</h4>
      <p>The Company does not provide users' personal information to outside parties in principle. However, exceptions are made in the following cases:</p>
      <p>• AI Technology Service Providers: The Company may share image data with AI technology partners to provide virtual try-on services. In this case, image data is used only for service processing purposes and is deleted immediately after processing is complete.</p>
      <h4 className="font-semibold text-foreground">Article 5 (Retention and Use Period of Personal Information)</h4>
      <p>• Photo image files (uploaded photos and result images): Deleted within 72 hours after service processing is complete</p>
      <p>• Virtual try-on result images automatically expire after 72 hours and are not permanently stored.</p>
      <h4 className="font-semibold text-foreground">Article 10 (Personal Information Protection Officer)</h4>
      <p>Name: Yejoon Jeong</p>
      <p>Email: admin@trukin.app</p>
      <p className="text-xs text-muted-foreground mt-6">Full Privacy Policy can be found via the link at the bottom of the service.</p>
    </div>
  );

  return (
    <main className="min-h-screen bg-background overflow-hidden">
      {/* Header */}
      <header className="fixed top-0 left-0 right-0 z-50 px-4 py-4">
        <div className="max-w-6xl mx-auto flex items-center justify-between">
          <Logo size="md" />
          <LanguageSwitch />
        </div>
      </header>

      {/* Login/Signup Section */}
      <section className="relative min-h-screen flex items-center justify-center px-4 pt-20 pb-16">
        {/* Background Elements */}
        <div className="absolute inset-0 overflow-hidden pointer-events-none">
          <div className="absolute top-32 right-[10%] w-80 h-80 bg-primary/10 rounded-full blur-3xl animate-float" />
          <div className="absolute bottom-32 left-[10%] w-96 h-96 bg-accent rounded-full blur-3xl animate-float" style={{ animationDelay: "-2.5s" }} />
        </div>

        <div className="relative z-10 w-full max-w-md mx-auto">
          <div className="bg-card border border-border rounded-3xl p-8 shadow-lg">
            {/* Badge */}
            <div className="flex justify-center mb-6">
              <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-accent text-accent-foreground">
                <Sparkles className="w-4 h-4" />
                <span className="text-sm font-semibold">{t("auth.badge")}</span>
              </div>
            </div>

            {/* Title */}
            <h1 className="font-display text-2xl md:text-3xl font-bold text-foreground text-center mb-2">
              {isSignup ? t("auth.signupTitle") : t("auth.title")}
            </h1>
            <p className="text-muted-foreground text-center mb-8">
              {isSignup ? t("auth.signupSubtitle") : t("auth.subtitle")}
            </p>

            {/* Agreement Section - Only shown for signup */}
            {isSignup && (
              <div className="space-y-3 mb-6">
                {/* Terms of Service */}
                <div 
                  className={`flex items-center gap-3 p-3 rounded-xl border transition-all cursor-pointer ${
                    termsRead 
                      ? "bg-primary/5 border-primary/30" 
                      : "bg-card border-border hover:border-primary/30"
                  }`}
                  onClick={() => !termsRead && setTermsDialogOpen(true)}
                >
                  <div className={`w-6 h-6 rounded-full flex items-center justify-center flex-shrink-0 ${
                    termsRead ? "bg-primary" : "border-2 border-muted-foreground/30"
                  }`}>
                    {termsRead && <Check className="w-4 h-4 text-primary-foreground" />}
                  </div>
                  <div className="flex-1 flex items-center gap-2">
                    <FileText className="w-4 h-4 text-muted-foreground" />
                    <span className="text-sm font-medium">{t("auth.termsLink")}</span>
                  </div>
                  {!termsRead && (
                    <span className="text-xs text-primary">{t("auth.readAndAgree")}</span>
                  )}
                </div>

                {/* Privacy Policy */}
                <div 
                  className={`flex items-center gap-3 p-3 rounded-xl border transition-all cursor-pointer ${
                    privacyRead 
                      ? "bg-primary/5 border-primary/30" 
                      : "bg-card border-border hover:border-primary/30"
                  }`}
                  onClick={() => !privacyRead && setPrivacyDialogOpen(true)}
                >
                  <div className={`w-6 h-6 rounded-full flex items-center justify-center flex-shrink-0 ${
                    privacyRead ? "bg-primary" : "border-2 border-muted-foreground/30"
                  }`}>
                    {privacyRead && <Check className="w-4 h-4 text-primary-foreground" />}
                  </div>
                  <div className="flex-1 flex items-center gap-2">
                    <Shield className="w-4 h-4 text-muted-foreground" />
                    <span className="text-sm font-medium">{t("auth.privacyLink")}</span>
                  </div>
                  {!privacyRead && (
                    <span className="text-xs text-primary">{t("auth.readAndAgree")}</span>
                  )}
                </div>
              </div>
            )}

            {/* Google Button */}
            <Button 
              onClick={handleGoogleLogin}
              variant="outline"
              size="lg"
              className="w-full flex items-center justify-center gap-3 h-14 text-base"
              disabled={!canProceed}
            >
              <svg className="w-5 h-5" viewBox="0 0 24 24">
                <path fill="currentColor" d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z" />
                <path fill="currentColor" d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z" />
                <path fill="currentColor" d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z" />
                <path fill="currentColor" d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z" />
              </svg>
              {isSignup ? t("auth.googleSignup") : t("auth.google")}
            </Button>
            
            {isSignup && !allAgreed && (
              <p className="text-xs text-muted-foreground text-center mt-2">
                {t("auth.agreeRequiredBoth")}
              </p>
            )}

            {/* Mode Switch */}
            <div className="mt-6 text-center">
              <p className="text-sm text-muted-foreground">
                {isSignup ? t("auth.switchToLogin") : t("auth.switchToSignup")}{" "}
                <button
                  onClick={() => {
                    setMode(isSignup ? "login" : "signup");
                    setTermsRead(false);
                    setPrivacyRead(false);
                  }}
                  className="text-primary font-semibold hover:underline"
                >
                  {isSignup ? t("auth.loginLink") : t("auth.signupLink")}
                </button>
              </p>
            </div>

            {/* Benefits - only shown for signup */}
            {isSignup && (
              <div className="mt-8 space-y-3">
                <p className="text-sm text-muted-foreground text-center mb-4">
                  {t("auth.benefits.title")}
                </p>
                <div className="flex items-center gap-3 text-sm">
                  <div className="w-6 h-6 rounded-full gradient-primary flex items-center justify-center flex-shrink-0">
                    <span className="text-white text-xs">✓</span>
                  </div>
                  <span className="text-foreground">{t("auth.benefits.1")}</span>
                </div>
                <div className="flex items-center gap-3 text-sm">
                  <div className="w-6 h-6 rounded-full gradient-primary flex items-center justify-center flex-shrink-0">
                    <span className="text-white text-xs">✓</span>
                  </div>
                  <span className="text-foreground">{t("auth.benefits.2")}</span>
                </div>
                <div className="flex items-center gap-3 text-sm">
                  <div className="w-6 h-6 rounded-full gradient-primary flex items-center justify-center flex-shrink-0">
                    <span className="text-white text-xs">✓</span>
                  </div>
                  <span className="text-foreground">{t("auth.benefits.3")}</span>
                </div>
              </div>
            )}
          </div>

          {/* Footer text */}
          <p className="text-xs text-muted-foreground text-center mt-6">
            {t("auth.terms")}
          </p>
        </div>
      </section>

      {/* Terms Dialog */}
      <Dialog open={termsDialogOpen} onOpenChange={setTermsDialogOpen}>
        <DialogContent className="max-w-lg max-h-[80vh]">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <FileText className="w-5 h-5" />
              {t("auth.termsLink")}
            </DialogTitle>
            <DialogDescription>
              {t("auth.readCarefully")}
            </DialogDescription>
          </DialogHeader>
          <ScrollArea className="h-[400px] pr-4">
            {termsContent}
          </ScrollArea>
          <DialogFooter>
            <Button variant="outline" onClick={() => setTermsDialogOpen(false)}>
              {t("auth.cancel")}
            </Button>
            <Button variant="gradient" onClick={handleTermsAgree}>
              {t("auth.agreeAndContinue")}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Privacy Dialog */}
      <Dialog open={privacyDialogOpen} onOpenChange={setPrivacyDialogOpen}>
        <DialogContent className="max-w-lg max-h-[80vh]">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Shield className="w-5 h-5" />
              {t("auth.privacyLink")}
            </DialogTitle>
            <DialogDescription>
              {t("auth.readCarefully")}
            </DialogDescription>
          </DialogHeader>
          <ScrollArea className="h-[400px] pr-4">
            {privacyContent}
          </ScrollArea>
          <DialogFooter>
            <Button variant="outline" onClick={() => setPrivacyDialogOpen(false)}>
              {t("auth.cancel")}
            </Button>
            <Button variant="gradient" onClick={handlePrivacyAgree}>
              {t("auth.agreeAndContinue")}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </main>
  );
};

export default Auth;
