import { useState } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { ScrollArea } from "@/components/ui/scroll-area";
import { useLanguage } from "@/contexts/LanguageContext";
import { useAuth } from "@/hooks/useAuth";
import { supabase } from "@/integrations/supabase/client";
import { FileText, Shield, Check } from "lucide-react";

const TermsConsentDialog = () => {
  const { t, language } = useLanguage();
  const { user, profile, refreshProfile } = useAuth();
  
  const [termsRead, setTermsRead] = useState(false);
  const [privacyRead, setPrivacyRead] = useState(false);
  const [viewingTerms, setViewingTerms] = useState(false);
  const [viewingPrivacy, setViewingPrivacy] = useState(false);
  const [saving, setSaving] = useState(false);

  // Show only if user is logged in but hasn't agreed to terms
  const shouldShow = !!user && !!profile && !profile.terms_agreed_at;

  const handleAgreeAll = async () => {
    if (!user) return;
    setSaving(true);
    const { error } = await supabase
      .from("profiles")
      .update({ terms_agreed_at: new Date().toISOString() } as any)
      .eq("user_id", user.id);
    
    if (!error) {
      await refreshProfile();
    }
    setSaving(false);
  };

  const allAgreed = termsRead && privacyRead;

  const termsContent = language === "ko" ? (
    <div className="space-y-4 text-sm text-muted-foreground">
      <h4 className="font-semibold text-foreground">제1조 (목적)</h4>
      <p>이 약관은 Trukin(이하 "회사")이 제공하는 TruPick 서비스(이하 "서비스")의 이용과 관련하여 회사와 이용자 간의 권리, 의무 및 책임사항을 규정함을 목적으로 합니다.</p>
      <h4 className="font-semibold text-foreground">제2조 (정의)</h4>
      <p>"서비스"란 인공지능(AI) 기술을 활용한 가상 의류 피팅 및 스타일 분석 서비스를 의미합니다.</p>
      <h4 className="font-semibold text-foreground">제7조 (AI 생성물에 대한 면책)</h4>
      <p>1. 본 서비스에서 생성되는 이미지는 인공지능(AI) 기술을 통해 합성된 결과물이며, 실제 착용 시의 외관, 핏, 색상 등과 차이가 있을 수 있습니다.</p>
      <p>2. 회사는 AI 생성 이미지의 정확성, 완전성, 또는 특정 목적에의 적합성을 보증하지 않습니다.</p>
      <p>3. 회원은 본 서비스의 결과물을 참고 자료로만 활용해야 하며, 이를 기반으로 한 구매 결정 등에 대해 회사는 책임을 지지 않습니다.</p>
      <h4 className="font-semibold text-foreground">제8조 (워터마크 및 출처 표시)</h4>
      <p>1. 본 서비스에서 생성된 모든 이미지에는 AI 생성물임을 나타내는 워터마크("by TruPick AI")가 포함됩니다.</p>
      <p>2. 회원은 해당 워터마크를 제거, 변경, 또는 가리는 행위를 해서는 안 됩니다.</p>
      <p className="text-xs text-muted-foreground mt-6">전체 이용약관은 서비스 하단의 이용약관 링크에서 확인하실 수 있습니다.</p>
    </div>
  ) : (
    <div className="space-y-4 text-sm text-muted-foreground">
      <h4 className="font-semibold text-foreground">Article 1 (Purpose)</h4>
      <p>These Terms govern the rights, duties, and responsibilities between Trukin ("Company") and users in connection with the TruPick service ("Service").</p>
      <h4 className="font-semibold text-foreground">Article 2 (Definitions)</h4>
      <p>"Service" refers to virtual clothing try-on and style analysis services utilizing artificial intelligence (AI) technology.</p>
      <h4 className="font-semibold text-foreground">Article 7 (Disclaimer for AI-Generated Content)</h4>
      <p>1. Images generated by this Service are synthesized using AI technology and may differ from actual appearance, fit, or color when worn.</p>
      <p>2. The Company does not guarantee the accuracy, completeness, or fitness for any particular purpose of AI-generated images.</p>
      <p>3. Members should use the Service results as reference only; the Company is not responsible for purchase decisions based on these results.</p>
      <h4 className="font-semibold text-foreground">Article 8 (Watermark and Attribution)</h4>
      <p>1. All images generated by this Service include a watermark ("by TruPick AI") indicating AI-generated content.</p>
      <p>2. Members must not remove, alter, or obscure this watermark.</p>
      <p className="text-xs text-muted-foreground mt-6">Full Terms of Service can be found via the link at the bottom of the service.</p>
    </div>
  );

  const privacyContent = language === "ko" ? (
    <div className="space-y-4 text-sm text-muted-foreground">
      <h4 className="font-semibold text-foreground">제1조 (개인정보 처리 목적)</h4>
      <p>Trukin(이하 "회사")은 다음의 목적을 위하여 개인정보를 처리합니다.</p>
      <h4 className="font-semibold text-foreground">제4조 (개인정보 제3자 제공)</h4>
      <p>• AI 기술 서비스 제공자: 회사는 가상 피팅 서비스 제공을 위해 AI 기술 파트너사와 이미지 데이터를 공유할 수 있습니다.</p>
      <h4 className="font-semibold text-foreground">제5조 (개인정보의 보유 및 이용 기간)</h4>
      <p>• 사진 이미지 파일: 서비스 처리 완료 후 72시간 이내 삭제</p>
      <h4 className="font-semibold text-foreground">제10조 (개인정보 보호책임자)</h4>
      <p>성명: 정예준 (Yejoon Jeong) | 이메일: admin@trukin.app</p>
      <p className="text-xs text-muted-foreground mt-6">전체 개인정보처리방침은 서비스 하단의 링크에서 확인하실 수 있습니다.</p>
    </div>
  ) : (
    <div className="space-y-4 text-sm text-muted-foreground">
      <h4 className="font-semibold text-foreground">Article 1 (Purpose of Processing Personal Information)</h4>
      <p>Trukin ("Company") processes personal information for the following purposes.</p>
      <h4 className="font-semibold text-foreground">Article 4 (Provision of Personal Information to Third Parties)</h4>
      <p>• AI Technology Service Providers: The Company may share image data with AI technology partners to provide virtual try-on services.</p>
      <h4 className="font-semibold text-foreground">Article 5 (Retention and Use Period)</h4>
      <p>• Photo image files: Deleted within 72 hours after service processing is complete</p>
      <h4 className="font-semibold text-foreground">Article 10 (Personal Information Protection Officer)</h4>
      <p>Name: Yejoon Jeong | Email: admin@trukin.app</p>
      <p className="text-xs text-muted-foreground mt-6">Full Privacy Policy can be found via the link at the bottom of the service.</p>
    </div>
  );

  if (!shouldShow) return null;

  return (
    <>
      {/* Main consent overlay */}
      <Dialog open={shouldShow && !viewingTerms && !viewingPrivacy} onOpenChange={() => {}}>
        <DialogContent className="max-w-md" onPointerDownOutside={(e) => e.preventDefault()} onEscapeKeyDown={(e) => e.preventDefault()}>
          <DialogHeader>
            <DialogTitle className="text-center text-lg">
              {language === "ko" ? "서비스 이용 동의" : "Terms Agreement Required"}
            </DialogTitle>
            <DialogDescription className="text-center">
              {language === "ko" 
                ? "서비스 이용을 위해 아래 약관에 동의해주세요." 
                : "Please agree to the following terms to use our service."}
            </DialogDescription>
          </DialogHeader>

          <div className="space-y-3 my-2">
            {/* Terms */}
            <div 
              className={`flex items-center gap-3 p-3 rounded-xl border transition-all cursor-pointer ${
                termsRead ? "bg-primary/5 border-primary/30" : "bg-card border-border hover:border-primary/30"
              }`}
              onClick={() => !termsRead && setViewingTerms(true)}
            >
              <div className={`w-6 h-6 rounded-full flex items-center justify-center flex-shrink-0 ${
                termsRead ? "bg-primary" : "border-2 border-muted-foreground/30"
              }`}>
                {termsRead && <Check className="w-4 h-4 text-primary-foreground" />}
              </div>
              <div className="flex-1 flex items-center gap-2">
                <FileText className="w-4 h-4 text-muted-foreground" />
                <span className="text-sm font-medium">{t("auth.termsLink")}</span>
              </div>
              {!termsRead && <span className="text-xs text-primary">{t("auth.readAndAgree")}</span>}
            </div>

            {/* Privacy */}
            <div 
              className={`flex items-center gap-3 p-3 rounded-xl border transition-all cursor-pointer ${
                privacyRead ? "bg-primary/5 border-primary/30" : "bg-card border-border hover:border-primary/30"
              }`}
              onClick={() => !privacyRead && setViewingPrivacy(true)}
            >
              <div className={`w-6 h-6 rounded-full flex items-center justify-center flex-shrink-0 ${
                privacyRead ? "bg-primary" : "border-2 border-muted-foreground/30"
              }`}>
                {privacyRead && <Check className="w-4 h-4 text-primary-foreground" />}
              </div>
              <div className="flex-1 flex items-center gap-2">
                <Shield className="w-4 h-4 text-muted-foreground" />
                <span className="text-sm font-medium">{t("auth.privacyLink")}</span>
              </div>
              {!privacyRead && <span className="text-xs text-primary">{t("auth.readAndAgree")}</span>}
            </div>
          </div>

          <DialogFooter>
            <Button 
              variant="gradient" 
              className="w-full" 
              disabled={!allAgreed || saving}
              onClick={handleAgreeAll}
            >
              {saving 
                ? (language === "ko" ? "저장 중..." : "Saving...") 
                : (language === "ko" ? "동의하고 시작하기" : "Agree & Continue")}
            </Button>
          </DialogFooter>
          
          {!allAgreed && (
            <p className="text-xs text-muted-foreground text-center">
              {t("auth.agreeRequiredBoth")}
            </p>
          )}
        </DialogContent>
      </Dialog>

      {/* Terms Detail Dialog */}
      <Dialog open={viewingTerms} onOpenChange={setViewingTerms}>
        <DialogContent className="max-w-lg max-h-[80vh]">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <FileText className="w-5 h-5" />
              {t("auth.termsLink")}
            </DialogTitle>
            <DialogDescription>{t("auth.readCarefully")}</DialogDescription>
          </DialogHeader>
          <ScrollArea className="h-[400px] pr-4">{termsContent}</ScrollArea>
          <DialogFooter>
            <Button variant="outline" onClick={() => setViewingTerms(false)}>{t("auth.cancel")}</Button>
            <Button variant="gradient" onClick={() => { setTermsRead(true); setViewingTerms(false); }}>
              {t("auth.agreeAndContinue")}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Privacy Detail Dialog */}
      <Dialog open={viewingPrivacy} onOpenChange={setViewingPrivacy}>
        <DialogContent className="max-w-lg max-h-[80vh]">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Shield className="w-5 h-5" />
              {t("auth.privacyLink")}
            </DialogTitle>
            <DialogDescription>{t("auth.readCarefully")}</DialogDescription>
          </DialogHeader>
          <ScrollArea className="h-[400px] pr-4">{privacyContent}</ScrollArea>
          <DialogFooter>
            <Button variant="outline" onClick={() => setViewingPrivacy(false)}>{t("auth.cancel")}</Button>
            <Button variant="gradient" onClick={() => { setPrivacyRead(true); setViewingPrivacy(false); }}>
              {t("auth.agreeAndContinue")}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </>
  );
};

export default TermsConsentDialog;
